using System.Collections.Generic;

namespace ConfigApp
{
    public static class Effects
    {
        public struct EffectInfo
        {
            public EffectInfo(string name, EffectCategory effectCategory, string id, bool isTimed = false, bool isShort = false)
            {
                Name = name;
                EffectCategory = effectCategory;
                Id = id;
                IsTimed = isTimed;
                IsShort = isShort;
            }

            public readonly string Name;
            public readonly EffectCategory EffectCategory;
            public readonly string Id;
            public readonly bool IsTimed;
            public readonly bool IsShort;
        }

        public enum EffectCategory
        {
            PLAYER,
            VEHICLE,
            PEDS,
            TIME,
            WEATHER,
            MISC,
            META
        }

        public enum EffectTimedType
        {
            TIMED_NORMAL,
            TIMED_SHORT
        }

        public enum EffectType
        {
            EFFECT_PLAYER_SUICIDE,
            EFFECT_PLUS_2_STARS,
            EFFECT_5_STARS,
            EFFECT_NEVER_WANTED,
            EFFECT_STRIP_WEAPONS,
            EFFECT_HEAL,
            EFFECT_IGNITE,
            EFFECT_ANGRY_JESUS,
            EFFECT_SPAWN_IMPOTENTRAGE,
            EFFECT_ANGRY_JESUS2,
            EFFECT_IGNITE_PEDS,
            EFFECT_EXPLODE_VEHS,
            EFFECT_PLAYER_LAUNCH,
            EFFECT_VEHS_LAUNCH,
            EFFECT_PLAYER_VEH_LOCK,
            EFFECT_NOTHING,
            EFFECT_KILL_ENGINE,
            EFFECT_TIME_MORNING,
            EFFECT_TIME_DAY,
            EFFECT_TIME_EVENING,
            EFFECT_TIME_NIGHT,
            EFFECT_WEATHER_EXTRASUNNY,
            EFFECT_WEATHER_THUNDER,
            EFFECT_WEATHER_FOGGY,
            EFFECT_WEATHER_NEUTRAL,
            EFFECT_WEATHER_XMAS,
            EFFECT_TP_LSAIRPORT,
            EFFECT_TP_MAZETOWER,
            EFFECT_TP_FORTZANCUDO,
            EFFECT_TP_MOUNTCHILLIAD,
            EFFECT_TP_SKYFALL,
            EFFECT_TP_RANDOM,
            EFFECT_TP_MISSION,
            EFFECT_TP_FAKE,
            EFFECT_NO_PHONE,
            EFFECT_SET_INTO_CLOSEST_VEH,
            EFFECT_PEDS_EXIT_VEH,
            EFFECT_GAMESPEED_X05,
            EFFECT_GAMESPEED_X02,
            EFFECT_GAMESPEED_LAG,
            EFFECT_PEDS_RIOT,
            EFFECT_RED_VEHS,
            EFFECT_BLUE_VEHS,
            EFFECT_GREEN_VEHS,
            EFFECT_CHROME_VEHS,
            EFFECT_PINK_VEHS,
            EFFECT_RAINBOW_VEHS,
            EFFECT_FORCED_FP,
            EFFECT_SLIPPERY_VEHS,
            EFFECT_NO_GRAV_VEHS,
            EFFECT_PLAYER_INVINCIBLE,
            EFFECT_2XENGINE_VEHS,
            EFFECT_10XENGINE_VEHS,
            EFFECT_05XENGINE_VEHS,
            EFFECT_SPAWN_TANK,
            EFFECT_SPAWN_ADDER,
            EFFECT_SPAWN_DUMP,
            EFFECT_SPAWN_MONSTER,
            EFFECT_SPAWN_BMX,
            EFFECT_SPAWN_TUG,
            EFFECT_SPAWN_CARGO,
            EFFECT_SPAWN_BUS,
            EFFECT_SPAWN_BLIMP,
            EFFECT_SPAWN_BUZZARD,
            EFFECT_SPAWN_FAGGIO,
            EFFECT_SPAWN_RUINER3,
            EFFECT_SPAWN_BALETRAILER,
            EFFECT_SPAWN_ROMERO,
            EFFECT_SPAWN_RANDOM,
            EFFECT_NO_VEHS,
            EFFECT_EXPLODE_CUR_VEH,
            EFFECT_PEDS_INVISIBLE,
            EFFECT_VEHS_INVISIBLE,
            EFFECT_NO_RADAR,
            EFFECT_NO_HUD,
            EFFECT_SUPER_RUN,
            EFFECT_PLAYER_RAGDOLL,
            EFFECT_PEDS_RAGDOLL_ON_TOUCH,
            EFFECT_MINUS_100K,
            EFFECT_PEDS_FOLLOW_PLAYER,
            EFFECT_PLAYER_DRUNK,
            EFFECT_PEDS_OHKO,
            EFFECT_SCREEN_BLOOM,
            EFFECT_SCREEN_LSD,
            EFFECT_SCREEN_RENDERDIST,
            EFFECT_SCREEN_FOG,
            EFFECT_SCREEN_BRIGHT,
            EFFECT_SCREEN_MEXICO,
            EFFECT_SCREEN_FULLBRIGHT,
            EFFECT_SCREEN_BUBBLE_VISION,
            EFFECT_PEDS_BLIND,
            EFFECT_HONK_BOOSTING,
            EFFECT_MIN_DAMAGE,
            EFFECT_PEDS_FROZEN,
            EFFECT_LOW_GRAV,
            EFFECT_VERY_LOW_GRAV,
            EFFECT_INSANE_GRAV,
            EFFECT_INVERT_GRAV,
            EFFECT_VEH_REPAIR,
            EFFECT_VEH_POP_TIRES,
            EFFECT_ALL_VEH_POP_TIRES,
            EFFECT_NO_SPECIAL_ABILITY,
            EFFECT_IN_THE_HOOD,
            EFFECT_FORCED_CINEMATIC,
            EFFECT_PEDS_FLEE,
            EFFECT_BREAK_VEH_DOORS,
            EFFECT_ZOMBIES,
            EFFECT_METEOR_RAIN,
            EFFECT_BLACKOUT,
            EFFECT_QUICK_TIME,
            EFFECT_MOV_NO_UD,
            EFFECT_MOV_NO_LR,
            EFFECT_BREAK,
            EFFECT_EVERYONE_RPG,
            EFFECT_EVERYONE_TAZER,
            EFFECT_EVERYONE_MINIGUN,
            EFFECT_EVERYONE_UPNATOMIZER,
            EFFECT_EVERYONE_RANDOMWEP,
            EFFECT_EVERYONE_RAILGUN,
            EFFECT_EVERYONE_BATTLEAXE,
            EFFECT_NO_SPRINT_JUMP,
            EFFECT_EVERYONE_INVINCIBLE,
            EFFECT_VEHS_INVINCIBLE,
            EFFECT_PLAYER_SHOT_RAGDOLL,
            EFFECT_JUMPY_VEHS,
            EFFECT_LOCK_VEHS,
            EFFECT_TOTAL_CHAOS,
            EFFECT_NO_RAGDOLL,
            EFFECT_VEHS_HORN,
            EFFECT_TP_WAYPOINT,
            EFFECT_PEDS_SAY_HI,
            EFFECT_PEDS_INSULT,
            EFFECT_EXPLOSIVE_COMBAT,
            EFFECT_GIVE_ALL_WEPS,
            EFFECT_PEDS_AIMBOT,
            EFFECT_SPAWN_COMPANION_CHOP,
            EFFECT_SPAWN_COMPANION_CHIMP,
            EFFECT_SPAWN_COMPANION_BRAD,
            EFFECT_SPAWN_COMPANION_RANDOM,
            EFFECT_SPAWN_BALLA_SQUAD,
            EFFECT_PLAYER_NIGHTVISION,
            EFFECT_PLAYER_HEATVISION,
            EFFECT_PLAYER_MONEYDROPS,
            EFFECT_VEH_TPRANDOMPEDS,
            EFFECT_PEDS_REVIVE,
            EFFECT_SNOW,
            EFFECT_WHALE_RAIN,
            EFFECT_VEH_MAX_UPGRADES,
            EFFECT_VEH_RANDOM_UPGRADES,
            EFFECT_INTENSE_MUSIC,
            EFFECT_PEDS_DRIVEBY,
            EFFECT_PLAYER_RANDOMCLOTHES,
            EFFECT_PEDS_RAINBOWWEPS,
            EFFECT_GTAO_TRAFFIC,
            EFFECT_SPAWN_IE_SULTAN,
            EFFECT_PLAYER_SETINTORANDVEH,
            EFFECT_VEHS_FULLACCEL,
            EFFECT_SPAWN_UFO,
            EFFECT_SPAWN_FERRISWHEEL,
            EFFECT_EXPLOSIVE_PEDS,
            EFFECT_INVERTVELOCITY,
            EFFECT_PLAYER_TPEVERYTHING,
            EFFECT_WEATHER_RANDOMWEATHER,
            EFFECT_LOW_POLY,
            EFFECT_NEARBY_PEDS_OBLITERATE,
            EFFECT_VEHS_TRIGGER_ALARM,
            EFFECT_VEH_SET_RANDOM_SEAT,
            EFFECT_VEH_SET_TOPSPEED_30MPH,
            EFFECT_PEDS_RAGDOLL,
            EFFECT_JESUS_TAKE_THE_WHEEL,
            EFFECT_VEH_POP_TIRE_LOOP,
            EFFECT_ANGRY_ALIEN,
            EFFECT_ANGRY_JIMMY,
            EFFECT_OHKO_VEHICLES,
            EFFECT_VEH_SPAM_DOORS,
            EFFECT_VEH_SPEED_MINIMUM,
            EFFECT_MISC_LESTER,
            EFFECT_MISC_CREDITS,
            EFFECT_MISC_EARTHQUAKE,
            EFFECT_TP_FRONT,
            EFFECT_SPAWN_FAN_CATS,
            EFFECT_PEDS_COPS,
            EFFECT_ROT_ALL_VEHS,
            EFFECT_LAUNCH_ALL_PEDS,
            EFFECT_PEDS_ATTACK_PLAYER,
            EFFECT_CLONE_PLAYER,
            EFFECT_SLIDY_PEDS,
            EFFECT_SPAWN_DANCING_APES,
            EFFECT_ONE_BULLET_WEP,
            EFFECT_PHONES,
            EFFECT_MIDAS_TOUCH,
            EFFECT_SPAWN_RANDOM_HOSTILE,
            EFFECT_VEH_NO_BRAKES,
            EFFECT_PLAYER_PORTAL_GUN,
            EFFECT_MISC_FIREWORKS,
            EFFECT_VEH_DESPAWN,
            EFFECT_PEDS_SCOOTERBROTHERS,
            EFFECT_PEDS_INTORANDOMVEHS,
            EFFECT_PLAYER_HEAVY_RECOIL,
            EFFECT_PEDS_CAT_GUNS,
            EFFECT_PLAYER_FORCEFIELD,
            EFFECT_MISC_OIL_LEAKS,
            EFFECT_PEDS_GUNSMOKE,
            EFFECT_PLAYER_KEEP_RUNNING,
            EFFECT_VEH_WEAPONS,
            EFFECT_VEH_FLYING_CAR,
            EFFECT_MISC_AIRSTRIKE,
            EFFECT_MISC_DVDSCREENSAVER,
            EFFECT_PEDS_MERCENARIES,
            EFFECT_LOOSE_TRIGGER,
            EFFECT_PEDS_MINIONS,
            EFFECT_MISC_FLAMETHROWER,
            EFFECT_PLAYER_FAKEDEATH,
            EFFECT_VEH_REPLACEVEHICLE,
            EFFECT_PLAYER_KICKFLIP,
            EFFECT_GAMESPEED_SUPERHOT,
            EFFECT_VEH_BEYBLADE,
            EFFECT_KILLER_CLOWNS,
            EFFECT_JAMES_BOND,
            EFFECT_PLAYER_POOF,
            EFFECT_PLAYER_SIMEONSAYS,
            EFFECT_VEH_LOCKCAMERA,
            EFFECT_PLAYER_TIRED,
            EFFECT_SCREEN_LS_NOIRE,
            EFFECT_MISC_SUPER_STUNT,
            EFFECT_SCREEN_NEED_GLASSES,
            EFFECT_FLIP_CAMERA,
            EFFECT_PLAYER_WALK_ON_WATER,
            EFFECT_RAPID_FIRE,
            EFFECT_PLAYER_ON_DEMAND_CARTOON,
            EFFECT_PEDS_DRIVE_BACKWARDS,
            EFFECT_VEH_RANDTRAFFIC,
            EFFECT_MISC_RAMPJAM,
            EFFECT_MISC_VEHICLE_RAIN,
            EFFECT_MISC_CRASH,
            EFFECT_PLAYER_GRAVITY,
            EFFECT_VEHS_BOUNCY,
            EFFECT_PEDS_STOP_AND_STARE,
            EFFECT_PEDS_FLIP,
            EFFECT_PLAYER_PACIFIST,
            EFFECT_PEDS_BUSBOIS,
            EFFECT_PLAYER_DEAD_EYE,
            EFFECT_PLAYER_QUAKE_FOV,
            EFFECT_PLAYER_HACKING,
            EFFECT_PEDS_NAILGUNS,
            EFFECT_VEH_BRAKEBOOST,
            EFFECT_PLAYER_BEES,
            EFFECT_PLAYER_VR,
            EFFECT_MISC_PORTRAIT_MODE,
            EFFECT_HIGH_PITCH,
            EFFECT_NO_SKY,
            EFFECT_PLAYER_GTA_2,
            EFFECT_PEDS_KIFFLOM,
            EFFECT_META_TIMER_SPEED_X2,
            EFFECT_META_TIMER_SPEED_X5,
            EFFECT_META_TIMER_SPEED_X0_5,
            EFFECT_META_EFFECT_DURATION_X2,
            EFFECT_META_EFFECT_DURATION_X0_5,
            EFFECT_META_HIDE_CHAOS_UI,
            EFFECT_META_ADDITIONAL_EFFECTS,
            EFFECT_VEHS_CRUMBLE,
            EFFECT_MISC_FPS_LIMIT,
            EFFECT_META_NO_CHAOS,
            EFFECT_PEDS_ROASTING,
            _EFFECT_ENUM_MAX
        }

        public static readonly Dictionary<EffectType, EffectInfo> EffectsMap = new Dictionary<EffectType, EffectInfo>()
        {
            {EffectType.EFFECT_PLAYER_SUICIDE, new EffectInfo("Suicidio", EffectCategory.PLAYER, "player_suicide")},
            {EffectType.EFFECT_PLUS_2_STARS, new EffectInfo("+2 Estrellas Se Busca", EffectCategory.PLAYER, "player_plus2stars")},
            {EffectType.EFFECT_5_STARS, new EffectInfo("5 Estrellas Se Busca", EffectCategory.PLAYER, "player_5stars")},
            {EffectType.EFFECT_NEVER_WANTED, new EffectInfo("La Poli Te Ignora", EffectCategory.PLAYER, "player_neverwanted", true)},
            {EffectType.EFFECT_STRIP_WEAPONS, new EffectInfo("Quitar Armas A Todos", EffectCategory.PEDS, "peds_remweps")},
            {EffectType.EFFECT_HEAL, new EffectInfo("Salud, Armadura y 250k $", EffectCategory.PLAYER, "player_heal")},
            {EffectType.EFFECT_IGNITE, new EffectInfo("Prender Fuego Al Jugador", EffectCategory.PLAYER, "player_ignite")},
            {EffectType.EFFECT_ANGRY_JESUS, new EffectInfo("Spawn Jesucristo Campero", EffectCategory.PEDS, "spawn_grieferjesus")},
            {EffectType.EFFECT_SPAWN_IMPOTENTRAGE, new EffectInfo("Spawn Impotent Rage", EffectCategory.PEDS, "peds_spawnimrage")},
            {EffectType.EFFECT_ANGRY_JESUS2, new EffectInfo("Spawn Jesucristo Campero Extremo", EffectCategory.PEDS, "spawn_grieferjesus2")},
            {EffectType.EFFECT_IGNITE_PEDS, new EffectInfo("Prender Fuego A Los Personajes Cercanos", EffectCategory.PEDS, "peds_ignite")},
            {EffectType.EFFECT_EXPLODE_VEHS, new EffectInfo("Reventar Vehiculos Cercanos", EffectCategory.VEHICLE, "vehs_explode")},
            {EffectType.EFFECT_PLAYER_LAUNCH, new EffectInfo("Lanzar Jugador Arriba", EffectCategory.PLAYER, "player_upupaway")},
            {EffectType.EFFECT_VEHS_LAUNCH, new EffectInfo("Lanzar Todos los Vehiculos Arriba", EffectCategory.VEHICLE, "vehs_upupaway")},
            {EffectType.EFFECT_PLAYER_VEH_LOCK, new EffectInfo("Encerrar Jugador En Vehiculo Actual", EffectCategory.VEHICLE, "playerveh_lock", true)},
            {EffectType.EFFECT_NOTHING, new EffectInfo("Nada", EffectCategory.MISC, "nothing")},
            {EffectType.EFFECT_KILL_ENGINE, new EffectInfo("Romper Motor De Todos Los Vehiculos", EffectCategory.VEHICLE, "playerveh_killengine")},
            {EffectType.EFFECT_TIME_MORNING, new EffectInfo("Establecer Hora En El Amanecer", EffectCategory.TIME, "time_morning")},
            {EffectType.EFFECT_TIME_DAY, new EffectInfo("Establecer Hora En El Mediodia", EffectCategory.TIME, "time_day")},
            {EffectType.EFFECT_TIME_EVENING, new EffectInfo("Establecer Hora En El Atardecer", EffectCategory.TIME, "time_evening")},
            {EffectType.EFFECT_TIME_NIGHT, new EffectInfo("Establecer Hora En La Medianoche", EffectCategory.TIME, "time_night")},
            {EffectType.EFFECT_WEATHER_EXTRASUNNY, new EffectInfo("Clima Extra Soleado", EffectCategory.WEATHER, "weather_extrasunny")},
            {EffectType.EFFECT_WEATHER_THUNDER, new EffectInfo("Clima tormentoso", EffectCategory.WEATHER, "weather_stormy")},
            {EffectType.EFFECT_WEATHER_FOGGY, new EffectInfo("Clima Con Niebla", EffectCategory.WEATHER, "weather_foggy")},
            {EffectType.EFFECT_WEATHER_NEUTRAL, new EffectInfo("Clima Neutro", EffectCategory.WEATHER, "weather_neutral")},
            {EffectType.EFFECT_WEATHER_XMAS, new EffectInfo("Clima De Nieve", EffectCategory.WEATHER, "weather_snowy")},
            {EffectType.EFFECT_TP_LSAIRPORT, new EffectInfo("Teletransporte Al Aeropuerto De LS", EffectCategory.PLAYER, "tp_lsairport")},
            {EffectType.EFFECT_TP_MAZETOWER, new EffectInfo("Teletransporte A Encima De La Torre Maze", EffectCategory.PLAYER, "tp_mazebanktower")},
            {EffectType.EFFECT_TP_FORTZANCUDO, new EffectInfo("Teletransporte A Base Militar", EffectCategory.PLAYER, "tp_fortzancudo")},
            {EffectType.EFFECT_TP_SKYFALL, new EffectInfo("Teletransporte Al Cielo", EffectCategory.PLAYER, "tp_skyfall")},
            {EffectType.EFFECT_TP_MOUNTCHILLIAD, new EffectInfo("Teletransporte Al Monte Chilliad", EffectCategory.PLAYER, "tp_mountchilliad")},
            {EffectType.EFFECT_TP_RANDOM, new EffectInfo("Teletransporte Aleatorio", EffectCategory.PLAYER, "tp_random")},
            {EffectType.EFFECT_TP_MISSION, new EffectInfo("Teletransporte A Mision Aleatoria", EffectCategory.PLAYER, "tp_mission")},
            {EffectType.EFFECT_TP_FAKE, new EffectInfo("Teletransporte Falso", EffectCategory.PLAYER, "tp_fake")},
            {EffectType.EFFECT_NO_PHONE, new EffectInfo("Sin Telefono", EffectCategory.MISC, "player_nophone", true)},
            {EffectType.EFFECT_SET_INTO_CLOSEST_VEH, new EffectInfo("Meter Jugador En Vehiculo Mas Cercano", EffectCategory.PLAYER, "player_tpclosestveh")},
            {EffectType.EFFECT_PEDS_EXIT_VEH, new EffectInfo("Todos Salen De Sus Vehiculos", EffectCategory.PEDS, "playerveh_exit")},
            {EffectType.EFFECT_GAMESPEED_X02, new EffectInfo("Velocidad De Juego x0.2", EffectCategory.TIME, "time_x02", true, true)},
            {EffectType.EFFECT_GAMESPEED_X05, new EffectInfo("Velocidad De Juego x0.5", EffectCategory.TIME, "time_x05", true, true)},
            {EffectType.EFFECT_GAMESPEED_LAG, new EffectInfo("Lag", EffectCategory.MISC, "time_lag", true, true)},
            {EffectType.EFFECT_PEDS_RIOT, new EffectInfo("Modo Disturbios", EffectCategory.PEDS, "peds_riot", true)},
            {EffectType.EFFECT_RED_VEHS, new EffectInfo("Trafico Rojo", EffectCategory.VEHICLE, "vehs_red", true)},
            {EffectType.EFFECT_BLUE_VEHS, new EffectInfo("Trafico Azul", EffectCategory.VEHICLE, "vehs_blue", true)},
            {EffectType.EFFECT_GREEN_VEHS, new EffectInfo("Trafico Verde", EffectCategory.VEHICLE, "vehs_green", true)},
            {EffectType.EFFECT_CHROME_VEHS, new EffectInfo("Trafico Cromado", EffectCategory.VEHICLE, "vehs_chrome", true)},
            {EffectType.EFFECT_PINK_VEHS, new EffectInfo("Trafico Rosa", EffectCategory.VEHICLE, "vehs_pink", true)},
            {EffectType.EFFECT_RAINBOW_VEHS, new EffectInfo("Trafico Arcoiris", EffectCategory.VEHICLE, "vehs_rainbow", true)},
            {EffectType.EFFECT_FORCED_FP, new EffectInfo("Primera Persona", EffectCategory.MISC, "player_firstperson", true)},
            {EffectType.EFFECT_SLIPPERY_VEHS, new EffectInfo("Vehiculos Resbalosos", EffectCategory.VEHICLE, "vehs_slippery", true)},
            {EffectType.EFFECT_NO_GRAV_VEHS, new EffectInfo("Los Vehiculos No Tienen Gravedad", EffectCategory.VEHICLE, "vehs_nogravity", true, true)},
            {EffectType.EFFECT_PLAYER_INVINCIBLE, new EffectInfo("Invencibilidad", EffectCategory.PLAYER, "player_invincible", true)},
            {EffectType.EFFECT_2XENGINE_VEHS, new EffectInfo("Velocidad De Motor x2", EffectCategory.VEHICLE, "vehs_x2engine", true)},
            {EffectType.EFFECT_10XENGINE_VEHS, new EffectInfo("Velocidad De Motor x10", EffectCategory.VEHICLE, "vehs_x10engine", true)},
            {EffectType.EFFECT_05XENGINE_VEHS, new EffectInfo("Velocidad De Motor x0.5", EffectCategory.VEHICLE, "vehs_x05engine", true)},
            {EffectType.EFFECT_SPAWN_TANK, new EffectInfo("Spawn Tanque", EffectCategory.VEHICLE, "spawn_rhino")},
            {EffectType.EFFECT_SPAWN_ADDER, new EffectInfo("Spawn Super Deportivo", EffectCategory.VEHICLE, "spawn_adder")},
            {EffectType.EFFECT_SPAWN_DUMP, new EffectInfo("Spawn Camion De Carga", EffectCategory.VEHICLE, "spawn_dump")},
            {EffectType.EFFECT_SPAWN_MONSTER, new EffectInfo("Spawn Monster Truck", EffectCategory.VEHICLE, "spawn_monster")},
            {EffectType.EFFECT_SPAWN_BMX, new EffectInfo("Spawn Bici", EffectCategory.VEHICLE, "spawn_bmx")},
            {EffectType.EFFECT_SPAWN_TUG, new EffectInfo("Spawn Barco De Pesca", EffectCategory.VEHICLE, "spawn_tug")},
            {EffectType.EFFECT_SPAWN_CARGO, new EffectInfo("Spawn Avion De Carga", EffectCategory.VEHICLE, "spawn_cargo")},
            {EffectType.EFFECT_SPAWN_BUS, new EffectInfo("Spawn Bus", EffectCategory.VEHICLE, "spawn_bus")},
            {EffectType.EFFECT_SPAWN_BLIMP, new EffectInfo("Spawn Zepelin", EffectCategory.VEHICLE, "spawn_blimp")},
            {EffectType.EFFECT_SPAWN_BUZZARD, new EffectInfo("Spawn Helicoptero De Combate", EffectCategory.VEHICLE, "spawn_buzzard")},
            {EffectType.EFFECT_SPAWN_FAGGIO, new EffectInfo("Spawn Motillo", EffectCategory.VEHICLE, "spawn_faggio")},
            {EffectType.EFFECT_SPAWN_RUINER3, new EffectInfo("Spawn Ruiner Arruinado", EffectCategory.VEHICLE, "spawn_ruiner3")},
            {EffectType.EFFECT_SPAWN_BALETRAILER, new EffectInfo("Spawn Trailer De Heno", EffectCategory.VEHICLE, "spawn_baletrailer") },
            {EffectType.EFFECT_SPAWN_ROMERO, new EffectInfo("Donde es el funeral?", EffectCategory.VEHICLE, "spawn_romero") },
            {EffectType.EFFECT_SPAWN_RANDOM, new EffectInfo("Spawn Vehiculo Aleatorio", EffectCategory.VEHICLE, "spawn_random")},
            {EffectType.EFFECT_NO_VEHS, new EffectInfo("Sin Trafico", EffectCategory.VEHICLE, "notraffic", true)},
            {EffectType.EFFECT_EXPLODE_CUR_VEH, new EffectInfo("Reventar Vehiculo Actual", EffectCategory.VEHICLE, "playerveh_explode")},
            {EffectType.EFFECT_PEDS_INVISIBLE, new EffectInfo("Todo El Mundo Es Un Fantasma", EffectCategory.PEDS, "peds_ghost", true)},
            {EffectType.EFFECT_VEHS_INVISIBLE, new EffectInfo("Vehiculos Invisibles", EffectCategory.VEHICLE, "vehs_ghost", true)},
            {EffectType.EFFECT_NO_RADAR, new EffectInfo("Sin Radar", EffectCategory.MISC, "no_radar", true)},
            {EffectType.EFFECT_NO_HUD, new EffectInfo("Sin Interfaz", EffectCategory.MISC, "no_hud", true)},
            {EffectType.EFFECT_SUPER_RUN, new EffectInfo("Super Carrera & Super Salto", EffectCategory.PLAYER, "player_superrun", true)},
            {EffectType.EFFECT_PLAYER_RAGDOLL, new EffectInfo("El Jugador Se Cae", EffectCategory.PLAYER, "player_ragdoll")},
            {EffectType.EFFECT_PEDS_RAGDOLL, new EffectInfo("Todos Se Caen", EffectCategory.PEDS, "peds_ragdoll")},
            {EffectType.EFFECT_PEDS_RAGDOLL_ON_TOUCH, new EffectInfo("Sensible A Los Roces", EffectCategory.PEDS, "peds_sensitivetouch", true, true)},
            {EffectType.EFFECT_MINUS_100K, new EffectInfo("Bancarrota", EffectCategory.PLAYER, "poorboi")},
            {EffectType.EFFECT_PEDS_FOLLOW_PLAYER, new EffectInfo("Eres Famoso", EffectCategory.PEDS, "player_famous", true)},
            {EffectType.EFFECT_PLAYER_DRUNK, new EffectInfo("Borracho", EffectCategory.PLAYER, "player_drunk", true)},
            {EffectType.EFFECT_PEDS_OHKO, new EffectInfo("1 De Vida", EffectCategory.PEDS, "player_ohko", true)},
            {EffectType.EFFECT_SCREEN_BLOOM, new EffectInfo("Bloom", EffectCategory.MISC, "screen_bloom", true)},
            {EffectType.EFFECT_SCREEN_LSD, new EffectInfo("LSD", EffectCategory.PLAYER, "screen_lsd", true)},
            {EffectType.EFFECT_SCREEN_RENDERDIST, new EffectInfo("Donde Han Ido Todos?", EffectCategory.MISC, "screen_lowrenderdist", true, true)},
            {EffectType.EFFECT_SCREEN_FOG, new EffectInfo("Niebla Extrema", EffectCategory.MISC, "screen_fog", true, true)},
            {EffectType.EFFECT_SCREEN_LS_NOIRE, new EffectInfo("LS Noire", EffectCategory.MISC, "screen_lsnoire", true)},
            {EffectType.EFFECT_SCREEN_BRIGHT, new EffectInfo("Vision Frita", EffectCategory.MISC, "screen_bright", true, true)},
            {EffectType.EFFECT_SCREEN_MEXICO, new EffectInfo("Es Asi Como Se Ve Mexico?", EffectCategory.MISC, "screen_mexico", true)},
            {EffectType.EFFECT_SCREEN_FULLBRIGHT, new EffectInfo("A Tope De Brillo", EffectCategory.MISC, "screen_fullbright", true)},
            {EffectType.EFFECT_SCREEN_BUBBLE_VISION, new EffectInfo("Vision De Burbuja", EffectCategory.MISC, "screen_bubblevision", true, true)},
            {EffectType.EFFECT_PEDS_BLIND, new EffectInfo("Personajes Cegatos", EffectCategory.PEDS, "peds_blind", true)},
            {EffectType.EFFECT_HONK_BOOSTING, new EffectInfo("Turbo Claxon", EffectCategory.VEHICLE, "vehs_honkboost", true)},
            {EffectType.EFFECT_MIN_DAMAGE, new EffectInfo("No Hay Dolor", EffectCategory.PEDS, "peds_mindmg", true)},
            {EffectType.EFFECT_PEDS_FROZEN, new EffectInfo("Personajes Bobos", EffectCategory.PEDS, "peds_frozen", true)},
            {EffectType.EFFECT_LOW_GRAV, new EffectInfo("Baja Gravedad", EffectCategory.MISC, "lowgravity", true, true)},
            {EffectType.EFFECT_VERY_LOW_GRAV, new EffectInfo("Muy Baja Gravedad", EffectCategory.MISC, "verylowgravity", true, true)},
            {EffectType.EFFECT_INSANE_GRAV, new EffectInfo("Gravedad Insana", EffectCategory.MISC, "insanegravity", true, true)},
            {EffectType.EFFECT_INVERT_GRAV, new EffectInfo("Gravedad Invertida", EffectCategory.MISC, "invertgravity", true, true)},
            {EffectType.EFFECT_VEH_REPAIR, new EffectInfo("Reparar Todos Los Vehiculos", EffectCategory.VEHICLE, "playerveh_repair")},
            {EffectType.EFFECT_VEH_POP_TIRES, new EffectInfo("Reventar Todos Los Neumaticos", EffectCategory.VEHICLE, "playerveh_poptires")},
            {EffectType.EFFECT_ALL_VEH_POP_TIRES, new EffectInfo("Esto Si Que Son Neumaticos Reventando", EffectCategory.VEHICLE, "vehs_poptiresconstant", true, true)},
            {EffectType.EFFECT_NO_SPECIAL_ABILITY, new EffectInfo("Sin Habilidad especial", EffectCategory.PLAYER, "player_nospecial", true)},
            {EffectType.EFFECT_IN_THE_HOOD, new EffectInfo("Temazo, Loco", EffectCategory.PEDS, "peds_dance", true)},
            {EffectType.EFFECT_FORCED_CINEMATIC, new EffectInfo("Camara Cinematica En Vehiculos", EffectCategory.VEHICLE, "player_forcedcinematiccam", true)},
            {EffectType.EFFECT_PEDS_FLEE, new EffectInfo("Todos Huyen", EffectCategory.PEDS, "peds_flee")},
            {EffectType.EFFECT_BREAK_VEH_DOORS, new EffectInfo("Romper Todas Las Puertas", EffectCategory.VEHICLE, "playerveh_breakdoors")},
            {EffectType.EFFECT_ZOMBIES, new EffectInfo("Zombies Explosivos", EffectCategory.PEDS, "zombies", true)},
            {EffectType.EFFECT_METEOR_RAIN, new EffectInfo("Ducha De Meteoritos", EffectCategory.MISC, "meteorrain", true)},
            {EffectType.EFFECT_BLACKOUT, new EffectInfo("Apagon", EffectCategory.MISC, "world_blackout", true)},
            {EffectType.EFFECT_QUICK_TIME, new EffectInfo("Timelapse", EffectCategory.TIME, "time_quickday", true)},
            {EffectType.EFFECT_MOV_NO_UD, new EffectInfo("Desactivar Movimiento Adelante / Atras", EffectCategory.PLAYER, "player_noforwardbackward", true, true)},
            {EffectType.EFFECT_MOV_NO_LR, new EffectInfo("Desactivar Movimiento Izquierda / Derecha", EffectCategory.PLAYER, "player_noleftright", true, true)},
            {EffectType.EFFECT_BREAK, new EffectInfo("Piloto Automatico", EffectCategory.PLAYER, "player_break", true, true)},
            {EffectType.EFFECT_EVERYONE_RPG, new EffectInfo("Dar A Todos Un RPG", EffectCategory.PEDS, "peds_giverpg")},
            {EffectType.EFFECT_EVERYONE_TAZER, new EffectInfo("Dar A Todos Una Taser", EffectCategory.PEDS, "peds_stungun")},
            {EffectType.EFFECT_EVERYONE_MINIGUN, new EffectInfo("Dar A Todos Una Minigun", EffectCategory.PEDS, "peds_minigun")},
            {EffectType.EFFECT_EVERYONE_UPNATOMIZER, new EffectInfo("Dar A Todos Un Arma Alienigena", EffectCategory.PEDS, "peds_upnatomizer")},
            {EffectType.EFFECT_EVERYONE_RANDOMWEP, new EffectInfo("Dar A Todos Un Arma Aleatoria", EffectCategory.PEDS, "peds_randomwep")},
            {EffectType.EFFECT_EVERYONE_RAILGUN, new EffectInfo("Dar A Todos Un Arma De Rayos", EffectCategory.PEDS, "peds_railgun")},
            {EffectType.EFFECT_EVERYONE_BATTLEAXE, new EffectInfo("Dar A Todos Un Hacha De Batalla", EffectCategory.PEDS, "peds_battleaxe")},
            {EffectType.EFFECT_NO_SPRINT_JUMP, new EffectInfo("Sin Sprint & Sin Salto", EffectCategory.PLAYER, "player_nosprint", true)},
            {EffectType.EFFECT_EVERYONE_INVINCIBLE, new EffectInfo("Todo El Mundo Es Invencible", EffectCategory.PEDS, "peds_invincible", true)},
            {EffectType.EFFECT_VEHS_INVINCIBLE, new EffectInfo("Vehiculos Invulnerables", EffectCategory.VEHICLE, "vehs_invincible", true)},
            {EffectType.EFFECT_PLAYER_SHOT_RAGDOLL, new EffectInfo("Sensible A Los Tiros", EffectCategory.PLAYER, "player_ragdollondmg", true)},
            {EffectType.EFFECT_JUMPY_VEHS, new EffectInfo("Vehiculos Saltarines", EffectCategory.VEHICLE, "vehs_jumpy", true, true)},
            {EffectType.EFFECT_LOCK_VEHS, new EffectInfo("Bloquear Todos Los Vehiculos", EffectCategory.VEHICLE, "vehs_lockdoors")},
            {EffectType.EFFECT_TOTAL_CHAOS, new EffectInfo("Dia Del Juicio Final", EffectCategory.MISC, "chaosmode", true, true)},
            {EffectType.EFFECT_NO_RAGDOLL, new EffectInfo("Equilibrio De Acero", EffectCategory.PEDS, "player_noragdoll", true)},
            {EffectType.EFFECT_VEHS_HORN, new EffectInfo("Todos Los Vehiculos Pitan", EffectCategory.VEHICLE, "vehs_honkconstant", true)},
            {EffectType.EFFECT_TP_WAYPOINT, new EffectInfo("Teletransporte Al Punto De Ruta", EffectCategory.PLAYER, "player_tptowaypoint")},
            {EffectType.EFFECT_PEDS_SAY_HI, new EffectInfo("Vecindario Amigable", EffectCategory.PEDS, "peds_sayhi", true)},
            {EffectType.EFFECT_PEDS_INSULT, new EffectInfo("Vecindario Desagradable", EffectCategory.PEDS, "peds_insult", true)},
            {EffectType.EFFECT_EXPLOSIVE_COMBAT, new EffectInfo("Combate Explosivo", EffectCategory.PEDS, "player_explosivecombat", true)},
            {EffectType.EFFECT_GIVE_ALL_WEPS, new EffectInfo("Dar Todas Las Armas", EffectCategory.PLAYER, "player_allweps")},
            {EffectType.EFFECT_PEDS_AIMBOT, new EffectInfo("Ciudadanos Con Aimbot", EffectCategory.PEDS, "peds_aimbot", true)},
            {EffectType.EFFECT_SPAWN_COMPANION_CHOP, new EffectInfo("Spawn Perro Aliado", EffectCategory.PEDS, "spawn_chop")},
            {EffectType.EFFECT_SPAWN_COMPANION_CHIMP, new EffectInfo("Spawn Simio Aliado", EffectCategory.PEDS, "spawn_chimp")},
            {EffectType.EFFECT_SPAWN_COMPANION_BRAD, new EffectInfo("Spawn Brad Aliado", EffectCategory.PEDS, "spawn_compbrad")},
            {EffectType.EFFECT_SPAWN_COMPANION_RANDOM, new EffectInfo("Spawn Aliado Aleatorio", EffectCategory.PEDS, "spawn_comprnd")},
            {EffectType.EFFECT_PLAYER_NIGHTVISION, new EffectInfo("Vision Nocturna", EffectCategory.MISC, "player_nightvision", true)},
            {EffectType.EFFECT_PLAYER_HEATVISION, new EffectInfo("Vision Termica", EffectCategory.MISC, "player_heatvision", true, true)},
            {EffectType.EFFECT_PLAYER_MONEYDROPS, new EffectInfo("Lluvia De Dinero", EffectCategory.MISC, "player_moneydrops", true)},
            {EffectType.EFFECT_VEH_TPRANDOMPEDS, new EffectInfo("Meter Gente Aleatoria En El Vehiculo", EffectCategory.PEDS, "playerveh_tprandompeds")},
            {EffectType.EFFECT_PEDS_REVIVE, new EffectInfo("Revivir Personajes Muertos", EffectCategory.PEDS, "peds_revive")},
            {EffectType.EFFECT_SNOW, new EffectInfo("Nieve", EffectCategory.WEATHER, "world_snow", true)},
            {EffectType.EFFECT_WHALE_RAIN, new EffectInfo("Lluvia De Ballenas", EffectCategory.MISC, "world_whalerain", true)},
            {EffectType.EFFECT_VEH_MAX_UPGRADES, new EffectInfo("Mejorar Todos Los Vehiculos Al Maximo", EffectCategory.VEHICLE, "playerveh_maxupgrades")},
            {EffectType.EFFECT_VEH_RANDOM_UPGRADES, new EffectInfo("Mejorar Todos Los Vehiculos Aleatoriamente", EffectCategory.VEHICLE, "playerveh_randupgrades")},
            {EffectType.EFFECT_INTENSE_MUSIC, new EffectInfo("Reproducir Cancion De Arena Wars", EffectCategory.MISC, "player_arenawarstheme", true)},
            {EffectType.EFFECT_PEDS_DRIVEBY, new EffectInfo("Te Disparan Desde El Coche", EffectCategory.PEDS, "peds_driveby", true, true)},
            {EffectType.EFFECT_PLAYER_RANDOMCLOTHES, new EffectInfo("Ropa Aleatoria", EffectCategory.PLAYER, "player_randclothes")},
            {EffectType.EFFECT_PEDS_RAINBOWWEPS, new EffectInfo("Armas Arcoiris", EffectCategory.MISC, "peds_rainbowweps", true)},
            {EffectType.EFFECT_GTAO_TRAFFIC, new EffectInfo("Iman De Trafico", EffectCategory.VEHICLE, "traffic_gtao", true)},
            {EffectType.EFFECT_SPAWN_IE_SULTAN, new EffectInfo("Spawn Sultan Azul Enemigo", EffectCategory.VEHICLE, "spawn_bluesultan")},
            {EffectType.EFFECT_PLAYER_SETINTORANDVEH, new EffectInfo("Meter Jugador En Vehiculo Aleatorio", EffectCategory.PLAYER, "player_setintorandveh")},
            {EffectType.EFFECT_VEHS_FULLACCEL, new EffectInfo("Gas, Gas, Gas", EffectCategory.VEHICLE, "traffic_fullaccel", true, true)},
            {EffectType.EFFECT_SPAWN_UFO, new EffectInfo("Spawn OVNI", EffectCategory.MISC, "misc_spawnufo")},
            {EffectType.EFFECT_SPAWN_FERRISWHEEL, new EffectInfo("Spawn Noria", EffectCategory.MISC, "misc_spawnferriswheel")},
            {EffectType.EFFECT_EXPLOSIVE_PEDS, new EffectInfo("Peatones Explosivos", EffectCategory.PEDS, "peds_explosive", true)},
            {EffectType.EFFECT_INVERTVELOCITY, new EffectInfo("Invertir Velocidad Actual", EffectCategory.MISC, "invertvelocity")},
            {EffectType.EFFECT_PLAYER_TPEVERYTHING, new EffectInfo("Traer Todo Al Jugador", EffectCategory.PLAYER, "player_tpeverything")},
            {EffectType.EFFECT_WEATHER_RANDOMWEATHER, new EffectInfo("Clima Disco", EffectCategory.WEATHER, "weather_randomizer", true)},
            {EffectType.EFFECT_LOW_POLY, new EffectInfo("Graficos De PS1", EffectCategory.MISC, "world_lowpoly", true)},
            {EffectType.EFFECT_NEARBY_PEDS_OBLITERATE, new EffectInfo("Todos Los Peatones Explotan", EffectCategory.PEDS, "peds_obliterate")},
            {EffectType.EFFECT_VEHS_TRIGGER_ALARM, new EffectInfo("Suenan Las Alarmas", EffectCategory.VEHICLE, "vehs_alarmloop", true)},
            {EffectType.EFFECT_VEH_SET_RANDOM_SEAT, new EffectInfo("Cambiar De Asiento Al Jugador", EffectCategory.PLAYER, "veh_randomseat")},
            {EffectType.EFFECT_VEH_SET_TOPSPEED_30MPH, new EffectInfo("Limitador De Velocidad 30MPH", EffectCategory.VEHICLE, "veh_30mphlimit", true, true) },
            {EffectType.EFFECT_JESUS_TAKE_THE_WHEEL, new EffectInfo("Jesus Coge El Volante", EffectCategory.VEHICLE, "veh_jesustakethewheel")},
            {EffectType.EFFECT_VEH_POP_TIRE_LOOP, new EffectInfo("Las Ruedas Estallan Aleatoriamente", EffectCategory.VEHICLE, "veh_poptire", true, true)},
            {EffectType.EFFECT_ANGRY_ALIEN, new EffectInfo("Spawn Alien Enfadado", EffectCategory.PEDS, "peds_angryalien")},
            {EffectType.EFFECT_ANGRY_JIMMY, new EffectInfo("Spawn Jimmy El Celoso", EffectCategory.PEDS, "peds_angryjimmy")},
            {EffectType.EFFECT_OHKO_VEHICLES, new EffectInfo("Vehiculos Explotan Al Impactar", EffectCategory.VEHICLE, "vehs_ohko", true)},
            {EffectType.EFFECT_VEH_SPAM_DOORS, new EffectInfo("Puertas Automaticas", EffectCategory.VEHICLE, "vehs_spamdoors", true)},
            {EffectType.EFFECT_VEH_SPEED_MINIMUM, new EffectInfo("Need For Speed", EffectCategory.VEHICLE, "veh_speed_goal", true, true)},
            {EffectType.EFFECT_VEH_FLYING_CAR, new EffectInfo("Coches Voladores", EffectCategory.VEHICLE, "vehs_flyingcars", true)},
            {EffectType.EFFECT_MISC_LESTER, new EffectInfo("Pwned", EffectCategory.MISC, "misc_lester", true, true)},
            {EffectType.EFFECT_MISC_CREDITS, new EffectInfo("Pasar Los Creditos", EffectCategory.MISC, "misc_credits", true, true)},
            {EffectType.EFFECT_MISC_EARTHQUAKE, new EffectInfo("Terremoto", EffectCategory.MISC, "misc_earthquake", true, true)},
            {EffectType.EFFECT_TP_FRONT, new EffectInfo("Teletransportar Jugador Adelante", EffectCategory.PLAYER, "player_tpfront")},
            {EffectType.EFFECT_SPAWN_FAN_CATS, new EffectInfo("Spawn Gatos Amistosos", EffectCategory.PEDS, "peds_spawnfancats")},
            {EffectType.EFFECT_PEDS_COPS, new EffectInfo("Todos Los Peatones Son Policias", EffectCategory.PEDS, "peds_cops", true)},
            {EffectType.EFFECT_ROT_ALL_VEHS, new EffectInfo("Voltear Todos Los Vehiculos", EffectCategory.VEHICLE, "vehs_rotall")},
            {EffectType.EFFECT_LAUNCH_ALL_PEDS, new EffectInfo("Lanzar Peatones Arriba", EffectCategory.PEDS, "peds_launchnearby")},
            {EffectType.EFFECT_PEDS_ATTACK_PLAYER, new EffectInfo("Todos Atacan Al Jugador", EffectCategory.PEDS, "peds_attackplayer", true)},
            {EffectType.EFFECT_CLONE_PLAYER, new EffectInfo("Clonar Jugador", EffectCategory.PLAYER, "player_clone")},
            {EffectType.EFFECT_SLIDY_PEDS, new EffectInfo("Peatones Deslizantes", EffectCategory.PEDS, "peds_slidy", true, true)},
            {EffectType.EFFECT_SPAWN_DANCING_APES, new EffectInfo("Spawn Simios Bailarines", EffectCategory.PEDS, "peds_spawndancingapes")},
            {EffectType.EFFECT_ONE_BULLET_WEP, new EffectInfo("Cargadores De Una Bala", EffectCategory.PEDS, "misc_onebullet", true)},
            {EffectType.EFFECT_PHONES, new EffectInfo("De Quien Es El Movil?", EffectCategory.PEDS, "peds_phones", true)},
            {EffectType.EFFECT_MIDAS_TOUCH, new EffectInfo("Toque Dorado", EffectCategory.PLAYER, "misc_midas", true)},
            {EffectType.EFFECT_SPAWN_RANDOM_HOSTILE, new EffectInfo("Spawn Enemigo Aleatorio", EffectCategory.PEDS, "peds_spawnrandomhostile")},
            {EffectType.EFFECT_VEH_NO_BRAKES, new EffectInfo("Sin Frenos", EffectCategory.VEHICLE, "playerveh_nobrakes", true)},
            {EffectType.EFFECT_PLAYER_PORTAL_GUN, new EffectInfo("Armas De Portales", EffectCategory.PEDS, "peds_portal_gun", true)},
            {EffectType.EFFECT_MISC_FIREWORKS, new EffectInfo("Fuegos Artificiales!", EffectCategory.MISC, "misc_fireworks", true)},
            {EffectType.EFFECT_SPAWN_BALLA_SQUAD, new EffectInfo("Spawn Grupo Balla", EffectCategory.PEDS, "peds_spawnballasquad")},
            {EffectType.EFFECT_VEH_DESPAWN, new EffectInfo("Borrar Vehiculo Actual", EffectCategory.VEHICLE, "playerveh_despawn")},
            {EffectType.EFFECT_PEDS_SCOOTERBROTHERS, new EffectInfo("Hermanos De Motillo", EffectCategory.PEDS, "peds_scooterbrothers")},
            {EffectType.EFFECT_PEDS_INTORANDOMVEHS, new EffectInfo("Meter A Todos En Vehiculos Aleatorios", EffectCategory.PEDS, "peds_intorandomvehs")},
            {EffectType.EFFECT_PLAYER_HEAVY_RECOIL, new EffectInfo("Gran Retroceso De Las Armas", EffectCategory.PLAYER, "player_heavyrecoil", true)},
            {EffectType.EFFECT_PEDS_CAT_GUNS, new EffectInfo("Armas Gatunas", EffectCategory.PEDS, "peds_catguns", true)},
            {EffectType.EFFECT_PLAYER_FORCEFIELD, new EffectInfo("Campo De Fuerza", EffectCategory.PLAYER, "player_forcefield", true, true)},
            {EffectType.EFFECT_MISC_OIL_LEAKS, new EffectInfo("Rastros De Aceite", EffectCategory.MISC, "misc_oilleaks", true)},
            {EffectType.EFFECT_PEDS_GUNSMOKE, new EffectInfo("Armas Humeantes", EffectCategory.PEDS, "peds_gunsmoke", true)},
            {EffectType.EFFECT_PLAYER_KEEP_RUNNING, new EffectInfo("Ayuda, No Puedo Parar", EffectCategory.PLAYER, "player_keeprunning", true)},
            {EffectType.EFFECT_VEH_WEAPONS, new EffectInfo("Vehiculos Con Lanzamisiles", EffectCategory.VEHICLE, "veh_weapons", true)},
            {EffectType.EFFECT_MISC_AIRSTRIKE, new EffectInfo("Ataque Aereo En Camino", EffectCategory.MISC, "misc_airstrike", true)},
            {EffectType.EFFECT_PEDS_MERCENARIES, new EffectInfo("Mercenarios", EffectCategory.PEDS, "peds_mercenaries", true)},
            {EffectType.EFFECT_LOOSE_TRIGGER, new EffectInfo("Gatillo Suelto", EffectCategory.PEDS, "peds_loosetrigger", true)},
            {EffectType.EFFECT_PEDS_MINIONS, new EffectInfo("Minions", EffectCategory.PEDS, "peds_minions", true)},
            {EffectType.EFFECT_MISC_FLAMETHROWER, new EffectInfo("Lanzallamas", EffectCategory.MISC, "misc_flamethrower", true)},
            {EffectType.EFFECT_MISC_DVDSCREENSAVER, new EffectInfo("Fondo De Pantalla DVD", EffectCategory.MISC, "misc_dvdscreensaver", true, true)},
            {EffectType.EFFECT_PLAYER_FAKEDEATH, new EffectInfo("Muerte Falsa", EffectCategory.PLAYER, "player_fakedeath")},
            {EffectType.EFFECT_GAMESPEED_SUPERHOT, new EffectInfo("Superhot", EffectCategory.TIME, "time_superhot", true)},
            {EffectType.EFFECT_VEH_BEYBLADE, new EffectInfo("Beyblades", EffectCategory.VEHICLE, "vehs_beyblade", true, true)},
            {EffectType.EFFECT_KILLER_CLOWNS, new EffectInfo("Payasos Asesinos", EffectCategory.PEDS, "peds_killerclowns", true, true)},
            {EffectType.EFFECT_JAMES_BOND, new EffectInfo("Spawn Agente Mortifero", EffectCategory.PEDS, "peds_jamesbond")},
            {EffectType.EFFECT_PLAYER_POOF, new EffectInfo("Punteria Letal", EffectCategory.PLAYER, "player_poof", true)},
            {EffectType.EFFECT_PLAYER_SIMEONSAYS, new EffectInfo("Simeon Dice", EffectCategory.PLAYER, "player_simeonsays", true, true)},
            {EffectType.EFFECT_VEH_LOCKCAMERA,  new EffectInfo("Bloquear Camara En Vehiculos", EffectCategory.VEHICLE, "veh_lockcamera", true)},
            {EffectType.EFFECT_VEH_REPLACEVEHICLE, new EffectInfo("Intercambiar Vehiculo Actual", EffectCategory.VEHICLE, "misc_replacevehicle")},
            {EffectType.EFFECT_PLAYER_TIRED,  new EffectInfo("Estoy Tan Cansado...", EffectCategory.PLAYER, "player_tired", true)},
            {EffectType.EFFECT_PLAYER_KICKFLIP,  new EffectInfo("Kickflip", EffectCategory.PLAYER, "player_kickflip")},
            {EffectType.EFFECT_MISC_SUPER_STUNT,  new EffectInfo("Super Acrobacia", EffectCategory.MISC, "misc_superstunt")},
            {EffectType.EFFECT_PLAYER_WALK_ON_WATER,  new EffectInfo("Andar Sobre El Agua", EffectCategory.PLAYER, "player_walkonwater", true)},
            {EffectType.EFFECT_SCREEN_NEED_GLASSES,  new EffectInfo("Se Me Han Olvidado Las Gafas", EffectCategory.MISC, "screen_needglasses", true, true)},
            {EffectType.EFFECT_FLIP_CAMERA, new EffectInfo("Camara Invertida", EffectCategory.PLAYER, "player_flip_camera", true, true)},
            {EffectType.EFFECT_PLAYER_QUAKE_FOV,  new EffectInfo("Campo De Vision A Tope", EffectCategory.PLAYER, "player_quake_fov", true)},
            {EffectType.EFFECT_RAPID_FIRE, new EffectInfo("Fuego Rapido", EffectCategory.PLAYER, "player_rapid_fire", true)},
            {EffectType.EFFECT_PLAYER_ON_DEMAND_CARTOON, new EffectInfo("Netflix And Chill", EffectCategory.PLAYER, "player_on_demand_cartoon", true)},
            {EffectType.EFFECT_PEDS_DRIVE_BACKWARDS, new EffectInfo("Ciudadanos Conducen Marcha Atras", EffectCategory.PEDS, "peds_drive_backwards", true)},
            {EffectType.EFFECT_VEH_RANDTRAFFIC,  new EffectInfo("Trafico Aleatorio", EffectCategory.VEHICLE, "veh_randtraffic", true, true)},
            {EffectType.EFFECT_MISC_RAMPJAM, new EffectInfo("Salto Con Rampa", EffectCategory.MISC, "misc_rampjam", true)},
            {EffectType.EFFECT_MISC_VEHICLE_RAIN, new EffectInfo("Lluvia De Vehiculos", EffectCategory.MISC, "misc_vehicle_rain", true, true)},
            {EffectType.EFFECT_MISC_CRASH,  new EffectInfo("Crasheo Falso", EffectCategory.MISC, "misc_fakecrash")},
            {EffectType.EFFECT_PLAYER_GRAVITY,  new EffectInfo("Campo Gravitatorio", EffectCategory.PLAYER, "player_gravity", true, true)},
            {EffectType.EFFECT_VEHS_BOUNCY,  new EffectInfo("Vehiculos Rebotantes", EffectCategory.VEHICLE, "veh_bouncy", true, false)},
            {EffectType.EFFECT_PEDS_STOP_AND_STARE, new EffectInfo("Parate Y Mira", EffectCategory.PEDS, "peds_stop_stare")},
            {EffectType.EFFECT_PEDS_FLIP,  new EffectInfo("Peatones Rotatorios", EffectCategory.PEDS, "peds_flip", true)},
            {EffectType.EFFECT_PLAYER_PACIFIST,  new EffectInfo("Pacifista", EffectCategory.PLAYER, "player_pacifist", true, false)},
            {EffectType.EFFECT_PEDS_BUSBOIS,  new EffectInfo("Los Chicos Del Bus", EffectCategory.PEDS, "peds_busbois")},
            {EffectType.EFFECT_PLAYER_DEAD_EYE,  new EffectInfo("Ojo Tuerto", EffectCategory.PLAYER, "player_dead_eye", true)},
            {EffectType.EFFECT_PLAYER_HACKING, new EffectInfo("Hackeo Realista", EffectCategory.PLAYER, "player_hacking")},
            {EffectType.EFFECT_PEDS_NAILGUNS, new EffectInfo("Pistolas de clavos", EffectCategory.PEDS, "peds_nailguns", true, true)},
            {EffectType.EFFECT_VEH_BRAKEBOOST,  new EffectInfo("Turbo Freno", EffectCategory.VEHICLE, "veh_brakeboost", true)},
            {EffectType.EFFECT_PLAYER_BEES, new EffectInfo("ABEJAS!", EffectCategory.PLAYER, "player_bees", true)},
            {EffectType.EFFECT_PLAYER_VR, new EffectInfo("Modo VR", EffectCategory.PLAYER, "player_vr", true, true)},
            {EffectType.EFFECT_MISC_PORTRAIT_MODE, new EffectInfo("Modo Retrato", EffectCategory.MISC, "misc_portrait", true)},
            {EffectType.EFFECT_HIGH_PITCH, new EffectInfo("Te Me Bajas 2 Tonitos, Nota", EffectCategory.MISC, "misc_highpitch", true)},
            {EffectType.EFFECT_NO_SKY, new EffectInfo("Sin Cielo", EffectCategory.MISC, "misc_nosky", true)},
            {EffectType.EFFECT_PLAYER_GTA_2, new EffectInfo("GTA 2", EffectCategory.PLAYER, "player_gta_2", true, true)},
            {EffectType.EFFECT_PEDS_KIFFLOM, new EffectInfo("Kifflom!", EffectCategory.PEDS, "peds_kifflom", true)},
            {EffectType.EFFECT_META_TIMER_SPEED_X0_5, new EffectInfo("Velocidad x0.5 De Cuenta Atras", EffectCategory.META, "meta_timerspeed_0_5x", true)},
            {EffectType.EFFECT_META_TIMER_SPEED_X2, new EffectInfo("Velocidad x2 De Cuenta Atras", EffectCategory.META, "meta_timerspeed_2x", true)},
            {EffectType.EFFECT_META_TIMER_SPEED_X5, new EffectInfo("Velocidad x5 De Cuenta Atras", EffectCategory.META, "meta_timerspeed_5x", true, true)},
            {EffectType.EFFECT_META_EFFECT_DURATION_X2, new EffectInfo("x2 Duracion De Efectos", EffectCategory.META, "meta_effect_duration_2x", true)},
            {EffectType.EFFECT_META_EFFECT_DURATION_X0_5, new EffectInfo("x0.5 Duracion De Efectos", EffectCategory.META, "meta_effect_duration_0_5x", true)},
            {EffectType.EFFECT_META_HIDE_CHAOS_UI, new EffectInfo("Que Esta Pasando??", EffectCategory.META, "meta_hide_chaos_ui", true)},
            {EffectType.EFFECT_META_ADDITIONAL_EFFECTS, new EffectInfo("Combo De Efectos", EffectCategory.META, "meta_spawn_multiple_effects", true)},
            {EffectType.EFFECT_VEHS_CRUMBLE, new EffectInfo("Vehiculos Hechos Chatarra", EffectCategory.VEHICLE, "vehs_crumble", true, true)},
            {EffectType.EFFECT_MISC_FPS_LIMIT, new EffectInfo("Experiencia De Consola", EffectCategory.MISC, "misc_fps_limit", true, true)},
            {EffectType.EFFECT_META_NO_CHAOS, new EffectInfo("Sin Caos", EffectCategory.META, "meta_nochaos", true)},
            {EffectType.EFFECT_PEDS_ROASTING, new EffectInfo("Humillacion", EffectCategory.PEDS, "peds_roasting", true, true)}
        };
    }
}
