#pragma once

#include <unordered_map>
#include <vector>

enum EffectType
{
	EFFECT_PLAYER_SUICIDE,
	EFFECT_PLUS_2_STARS,
	EFFECT_5_STARS,
	EFFECT_NEVER_WANTED,
	EFFECT_STRIP_WEAPONS,
	EFFECT_HEAL,
	EFFECT_IGNITE,
	EFFECT_ANGRY_JESUS,
	EFFECT_SPAWN_IMPOTENTRAGE,
	EFFECT_ANGRY_JESUS2,
	EFFECT_IGNITE_PEDS,
	EFFECT_EXPLODE_VEHS,
	EFFECT_PLAYER_LAUNCH,
	EFFECT_VEHS_LAUNCH,
	EFFECT_PLAYER_VEH_LOCK,
	EFFECT_NOTHING,
	EFFECT_KILL_ENGINE,
	EFFECT_TIME_MORNING,
	EFFECT_TIME_DAY,
	EFFECT_TIME_EVENING,
	EFFECT_TIME_NIGHT,
	EFFECT_WEATHER_EXTRASUNNY,
	EFFECT_WEATHER_THUNDER,
	EFFECT_WEATHER_FOGGY,
	EFFECT_WEATHER_NEUTRAL,
	EFFECT_WEATHER_XMAS,
	EFFECT_TP_LSAIRPORT,
	EFFECT_TP_MAZETOWER,
	EFFECT_TP_FORTZANCUDO,
	EFFECT_TP_MOUNTCHILLIAD,
	EFFECT_TP_SKYFALL,
	EFFECT_TP_RANDOM,
	EFFECT_TP_MISSION,
	EFFECT_TP_FAKE,
	EFFECT_NO_PHONE,
	EFFECT_SET_INTO_CLOSEST_VEH,
	EFFECT_PEDS_EXIT_VEH,
	EFFECT_GAMESPEED_X05,
	EFFECT_GAMESPEED_X02,
	EFFECT_GAMESPEED_LAG,
	EFFECT_PEDS_RIOT,
	EFFECT_RED_VEHS,
	EFFECT_BLUE_VEHS,
	EFFECT_GREEN_VEHS,
	EFFECT_CHROME_VEHS,
	EFFECT_PINK_VEHS,
	EFFECT_RAINBOW_VEHS,
	EFFECT_FORCED_FP,
	EFFECT_SLIPPERY_VEHS,
	EFFECT_NO_GRAV_VEHS,
	EFFECT_PLAYER_INVINCIBLE,
	EFFECT_2XENGINE_VEHS,
	EFFECT_10XENGINE_VEHS,
	EFFECT_05XENGINE_VEHS,
	EFFECT_SPAWN_TANK,
	EFFECT_SPAWN_ADDER,
	EFFECT_SPAWN_DUMP,
	EFFECT_SPAWN_MONSTER,
	EFFECT_SPAWN_BMX,
	EFFECT_SPAWN_TUG,
	EFFECT_SPAWN_CARGO,
	EFFECT_SPAWN_BUS,
	EFFECT_SPAWN_BLIMP,
	EFFECT_SPAWN_BUZZARD,
	EFFECT_SPAWN_FAGGIO,
	EFFECT_SPAWN_RUINER3,
	EFFECT_SPAWN_BALETRAILER,
	EFFECT_SPAWN_ROMERO,
	EFFECT_SPAWN_RANDOM,
	EFFECT_NO_VEHS,
	EFFECT_EXPLODE_CUR_VEH,
	EFFECT_PEDS_INVISIBLE,
	EFFECT_VEHS_INVISIBLE,
	EFFECT_NO_RADAR,
	EFFECT_NO_HUD,
	EFFECT_SUPER_RUN,
	EFFECT_PLAYER_RAGDOLL,
	EFFECT_PEDS_RAGDOLL,
	EFFECT_PEDS_RAGDOLL_ON_TOUCH,
	EFFECT_PLAYER_POOR,
	EFFECT_PEDS_FOLLOW_PLAYER,
	EFFECT_PLAYER_DRUNK,
	EFFECT_PEDS_OHKO,
	EFFECT_SCREEN_BLOOM,
	EFFECT_SCREEN_LSD,
	EFFECT_SCREEN_RENDERDIST,
	EFFECT_SCREEN_FOG,
	EFFECT_SCREEN_BRIGHT,
	EFFECT_SCREEN_MEXICO,
	EFFECT_SCREEN_FULLBRIGHT,
	EFFECT_SCREEN_BUBBLEVISION,
	EFFECT_PEDS_BLIND,
	EFFECT_HONK_BOOSTING,
	EFFECT_MIN_DAMAGE,
	EFFECT_PEDS_FROZEN,
	EFFECT_LOW_GRAV,
	EFFECT_VERY_LOW_GRAV,
	EFFECT_INSANE_GRAV,
	EFFECT_INVERT_GRAV,
	EFFECT_VEH_REPAIR,
	EFFECT_VEH_POP_TIRES,
	EFFECT_ALL_VEH_POP_TIRES,
	EFFECT_NO_SPECIAL_ABILITY,
	EFFECT_IN_THE_HOOD,
	EFFECT_FORCED_CINEMATIC,
	EFFECT_PEDS_FLEE,
	EFFECT_BREAK_VEH_DOORS,
	EFFECT_ZOMBIES,
	EFFECT_METEOR_RAIN,
	EFFECT_BLACKOUT,
	EFFECT_QUICK_TIME,
	EFFECT_MOV_NO_UD,
	EFFECT_MOV_NO_LR,
	EFFECT_PLAYER_AUTOPILOT,
	EFFECT_EVERYONE_RPG,
	EFFECT_EVERYONE_TAZER,
	EFFECT_EVERYONE_MINIGUN,
	EFFECT_EVERYONE_UPNATOMIZER,
	EFFECT_EVERYONE_RANDOMWEP,
	EFFECT_EVERYONE_RAILGUN,
	EFFECT_EVERYONE_BATTLEAXE,
	EFFECT_NO_SPRINT_JUMP,
	EFFECT_EVERYONE_INVINCIBLE,
	EFFECT_VEHS_INVINCIBLE,
	EFFECT_PLAYER_SHOT_RAGDOLL,
	EFFECT_JUMPY_VEHS,
	EFFECT_LOCK_VEHS,
	EFFECT_TOTAL_CHAOS,
	EFFECT_NO_RAGDOLL,
	EFFECT_VEHS_HORN,
	EFFECT_TP_WAYPOINT,
	EFFECT_PEDS_SAY_HI,
	EFFECT_PEDS_INSULT,
	EFFECT_EXPLOSIVE_COMBAT,
	EFFECT_GIVE_ALL_WEPS,
	EFFECT_PEDS_AIMBOT,
	EFFECT_SPAWN_COMPANION_CHOP,
	EFFECT_SPAWN_COMPANION_CHIMP,
	EFFECT_SPAWN_COMPANION_BRAD,
	EFFECT_SPAWN_COMPANION_RANDOM,
	EFFECT_SPAWN_BALLA_SQUAD,
	EFFECT_PLAYER_NIGHTVISION,
	EFFECT_PLAYER_HEATVISION,
	EFFECT_PLAYER_MONEYDROPS,
	EFFECT_VEH_TPRANDOMPEDS,
	EFFECT_PEDS_REVIVE,
	EFFECT_SNOW,
	EFFECT_WHALE_RAIN,
	EFFECT_VEH_MAX_UPGRADES,
	EFFECT_VEH_RANDOM_UPGRADES,
	EFFECT_INTENSE_MUSIC,
	EFFECT_PEDS_DRIVEBY,
	EFFECT_PLAYER_RANDOMCLOTHES,
	EFFECT_PEDS_RAINBOWWEPS,
	EFFECT_GTAO_TRAFFIC,
	EFFECT_SPAWN_IE_SULTAN,
	EFFECT_PLAYER_SETINTORANDVEH,
	EFFECT_VEHS_FULLACCEL,
	EFFECT_SPAWN_UFO,
	EFFECT_SPAWN_FERRISWHEEL,
	EFFECT_EXPLOSIVE_PEDS,
	EFFECT_INVERTVELOCITY,
	EFFECT_PLAYER_TPEVERYTHING,
	EFFECT_WEATHER_RANDOMWEATHER,
	EFFECT_LOW_POLY,
	EFFECT_NEARBY_PEDS_OBLITERATE,
	EFFECT_VEHS_TRIGGER_ALARM,
	EFFECT_VEH_SET_RANDOM_SEAT,
	EFFECT_VEH_SET_TOPSPEED_30MPH,
	EFFECT_JESUS_TAKE_THE_WHEEL,
	EFFECT_VEH_POP_TIRE_LOOP,
	EFFECT_ANGRY_ALIEN,
	EFFECT_ANGRY_JIMMY,
	EFFECT_OHKO_VEHICLES,
	EFFECT_VEH_SPAM_DOORS,
	EFFECT_VEH_SPEED_MINIMUM,
	EFFECT_MISC_LESTER,
	EFFECT_MISC_CREDITS,
	EFFECT_MISC_EARTHQUAKE,
	EFFECT_TP_FRONT,
	EFFECT_SPAWN_FAN_CATS,
	EFFECT_PEDS_COPS,
	EFFECT_ROT_ALL_VEHS,
	EFFECT_LAUNCH_ALL_PEDS,
	EFFECT_PEDS_ATTACK_PLAYER,
	EFFECT_CLONE_PLAYER,
	EFFECT_SLIDY_PEDS,
	EFFECT_SPAWN_DANCING_APES,
	EFFECT_ONE_BULLET_WEP,
	EFFECT_PHONES,
	EFFECT_MIDAS_TOUCH,
	EFFECT_SPAWN_RANDOM_HOSTILE,
	EFFECT_VEH_NO_BRAKES,
	EFFECT_PEDS_PORTAL_GUN,
	EFFECT_MISC_FIREWORKS,
	EFFECT_VEH_DESPAWN,
	EFFECT_PEDS_SCOOTERBROTHERS,
	EFFECT_PEDS_INTORANDOMVEHS,
	EFFECT_VEH_FLYING_CAR,
	EFFECT_PLAYER_HEAVY_RECOIL,
	EFFECT_PEDS_CAT_GUNS,
	EFFECT_PLAYER_FORCEFIELD,
	EFFECT_MISC_OIL_LEAKS,
	EFFECT_PEDS_GUNSMOKE,
	EFFECT_PLAYER_KEEP_RUNNING,
	EFFECT_GAMESPEED_SUPERHOT,
	EFFECT_VEH_WEAPONS,
	EFFECT_MISC_AIRSTRIKE,
	EFFECT_PEDS_MINIONS,
	EFFECT_PEDS_MERCENARIES,
	EFFECT_LOOSE_TRIGGER,
	EFFECT_PLAYER_KICKFLIP,
	EFFECT_MISC_FLAMETHROWER,
	EFFECT_MISC_DVDSCREENSAVER,
	EFFECT_PLAYER_FAKEDEATH,
	EFFECT_VEH_BEYBLADE,
	EFFECT_KILLER_CLOWNS,
	EFFECT_JAMES_BOND,
	EFFECT_PLAYER_POOF,
	EFFECT_PLAYER_SIMEONSAYS,
	EFFECT_VEH_LOCKCAMERA,
	EFFECT_VEH_REPLACEVEHICLE,
	EFFECT_PLAYER_TIRED,
	EFFECT_SCREEN_LS_NOIRE,
	EFFECT_MISC_SUPER_STUNT,
	EFFECT_SCREEN_NEED_GLASSES,
	EFFECT_FLIP_CAMERA,
	EFFECT_PLAYER_WALK_ON_WATER,
	EFFECT_RAPID_FIRE,
	EFFECT_PLAYER_ON_DEMAND_CARTOON,
	EFFECT_PEDS_DRIVE_BACKWARDS,
	EFFECT_VEH_RANDTRAFFIC,
	EFFECT_MISC_RAMPJAM,
	EFFECT_MISC_VEHICLE_RAIN,
	EFFECT_MISC_CRASH,
	EFFECT_PLAYER_GRAVITY,
	EFFECT_VEH_BOUNCY,
	EFFECT_PEDS_STOP_AND_STARE,
	EFFECT_PEDS_FLIP,
	EFFECT_PLAYER_PACIFIST,
	EFFECT_PEDS_BUSBOIS,
	EFFECT_PLAYER_DEAD_EYE,
	EFFECT_PLAYER_QUAKE_FOV,
	EFFECT_PLAYER_HACKING,
	EFFECT_PEDS_NAILGUNS,
	EFFECT_VEH_BRAKEBOOST,
	EFFECT_PLAYER_BEES,
	EFFECT_PLAYER_VR,
	EFFECT_MISC_PORTRAIT_MODE,
	EFFECT_HIGH_PITCH,
	EFFECT_NO_SKY,
	EFFECT_PLAYER_GTA_2,
	EFFECT_PEDS_KIFFLOM,
	EFFECT_META_TIMER_SPEED_X0_5,
	EFFECT_META_TIMER_SPEED_X2,
	EFFECT_META_TIMER_SPEED_X5,
	EFFECT_META_EFFECT_DURATION_X2,
	EFFECT_META_EFFECT_DURATION_X0_5,
	EFFECT_META_HIDE_CHAOS_UI,
	EFFECT_META_ADDITIONAL_EFFECTS,
	EFFECT_VEHS_CRUMBLE,
	EFFECT_MISC_FPS_LIMIT,
	EFFECT_META_NO_CHAOS,
	EFFECT_PEDS_ROASTING,
	_EFFECT_ENUM_MAX
};

enum EffectExecutionType
{
	DEFAULT,
	META
};

struct EffectInfo
{
public:
	EffectInfo(const char* name, const char* id, bool isTimed = false, std::vector<EffectType> incompatibleList = {}, bool shortDur = false, EffectExecutionType type = EffectExecutionType::DEFAULT)
		: Name(name), Id(id), IsTimed(isTimed), IsShortDuration(shortDur), IncompatibleWith(incompatibleList), ExecutionType(type) {}

public:
	const char* Name;
	const char* Id;
	const bool IsTimed;
	const bool IsShortDuration;
	const std::vector<EffectType> IncompatibleWith;
	const EffectExecutionType ExecutionType;
};

const std::unordered_map<EffectType, EffectInfo> g_effectsMap =
{
	{EFFECT_PLAYER_SUICIDE, {"Suicidio", "player_suicide", false, {EFFECT_PLAYER_INVINCIBLE}}},
	{EFFECT_PLUS_2_STARS, {"+2 Estrellas Se Busca", "player_plus2stars", false, {EFFECT_NEVER_WANTED}}},
	{EFFECT_5_STARS, {"5 Estrellas Se Busca", "player_5stars", false, {EFFECT_NEVER_WANTED}}},
	{EFFECT_NEVER_WANTED, {"La Poli Te Ignora", "player_neverwanted", true}},
	{EFFECT_STRIP_WEAPONS, {"Quitar Armas A Todos", "peds_remweps"}},
	{EFFECT_HEAL, {"Salud, Armadura y 250$", "player_heal"}},
	{EFFECT_IGNITE, {"Prender Fuego Al Jugador", "player_ignite", false, {EFFECT_PLAYER_INVINCIBLE}}},
	{EFFECT_ANGRY_JESUS, {"Spawn Jesucristo Campero", "spawn_grieferjesus"}},
	{EFFECT_SPAWN_IMPOTENTRAGE, {"Spawn Impotent Rage", "peds_spawnimrage"}},




	{EFFECT_ANGRY_JESUS2, {"Spawn Jesucristo Campero Extremo", "spawn_grieferjesus2"}},
	{EFFECT_IGNITE_PEDS, {"Prender Fuego A Los Personajes Cercanos", "peds_ignite"}},
	{EFFECT_EXPLODE_VEHS, {"Reventar Vehiculos Cercanos", "vehs_explode"}},
	{EFFECT_PLAYER_LAUNCH, {"Lanzar Jugador Arriba", "player_upupaway"}},
	{EFFECT_VEHS_LAUNCH, {"Lanzar Todos los Vehiculos Arriba", "vehs_upupaway"}},
	{EFFECT_PLAYER_VEH_LOCK, {"Encerrar Jugador En Vehiculo Actual", "playerveh_lock", true}},
	{EFFECT_NOTHING, {"Nada", "nothing"}},
	{EFFECT_KILL_ENGINE, {"Romper Motor De Todos Los Vehiculos", "playerveh_killengine"}},
	{EFFECT_TIME_MORNING, {"Establecer Hora En El Amanecer", "time_morning"}},
	{EFFECT_TIME_DAY, {"Establecer Hora En El Mediodia", "time_day"}},
	{EFFECT_TIME_EVENING, {"Establecer Hora En El Atardecer", "time_evening"}},
	{EFFECT_TIME_NIGHT, {"Establecer Hora En La Medianoche", "time_night"}},
	{EFFECT_WEATHER_EXTRASUNNY, {"Clima Extra Soleado", "weather_extrasunny"}},
	{EFFECT_WEATHER_THUNDER, {"Clima tormentoso", "weather_stormy"}},
	{EFFECT_WEATHER_FOGGY, {"Clima Con Niebla", "weather_foggy"}},
	{EFFECT_WEATHER_NEUTRAL, {"Clima Neutro", "weather_neutral"}},
	{EFFECT_WEATHER_XMAS, {"Clima De Nieve", "weather_snowy"}},
	{EFFECT_TP_LSAIRPORT, {"Teletransporte Al Aeropuerto De LS", "tp_lsairport"}},
	{EFFECT_TP_MAZETOWER, {"Teletransporte A Encima De La Torre Maze", "tp_mazebanktower"}},
	{EFFECT_TP_FORTZANCUDO, {"Teletransporte A Base Militar", "tp_fortzancudo"}},
	{EFFECT_TP_MOUNTCHILLIAD, {"Teletransporte Al Monte Chilliad", "tp_mountchilliad"}},
	{EFFECT_TP_SKYFALL, {"Teletransporte Al Cielo", "tp_skyfall"}},
	{EFFECT_TP_RANDOM, {"Teletransporte Aleatorio", "tp_random"}},
	{EFFECT_TP_MISSION,  {"Teletransporte A Mision Aleatoria", "tp_mission"}},
	{EFFECT_TP_FAKE,  {"Teletransporte Falso", "tp_fake"}},
	{EFFECT_NO_PHONE, {"Sin Telefono", "player_nophone", true}},
	{EFFECT_SET_INTO_CLOSEST_VEH, {"Meter Jugador En Vehiculo Mas Cercano", "player_tpclosestveh"}},
	{EFFECT_PEDS_EXIT_VEH, {"Todos Salen De Sus Vehiculos", "playerveh_exit"}},
	{EFFECT_GAMESPEED_X02, {"Velocidad De Juego x0.2", "time_x02", true, { EFFECT_GAMESPEED_X05, EFFECT_GAMESPEED_LAG, EFFECT_PLAYER_DEAD_EYE }, true}},
	{EFFECT_GAMESPEED_X05, {"Velocidad De Juego x0.5", "time_x05", true, { EFFECT_GAMESPEED_X02, EFFECT_GAMESPEED_LAG, EFFECT_PLAYER_DEAD_EYE }, true}},
	{EFFECT_PLAYER_DEAD_EYE, {"Ojo Muerto", "player_dead_eye", true, { EFFECT_GAMESPEED_X05, EFFECT_GAMESPEED_X02, EFFECT_GAMESPEED_LAG }}},
	{EFFECT_GAMESPEED_LAG, {"Lag", "time_lag", true, {}, true}},
	{EFFECT_PEDS_RIOT, {"Modo Disturbios", "peds_riot", true, { EFFECT_PEDS_COPS }}},
	{EFFECT_RED_VEHS, {"Trafico Rojo", "vehs_red", true, { EFFECT_BLUE_VEHS, EFFECT_GREEN_VEHS, EFFECT_RAINBOW_VEHS, EFFECT_VEHS_INVISIBLE, EFFECT_PINK_VEHS }}},
	{EFFECT_BLUE_VEHS, {"Trafico Azul", "vehs_blue", true, { EFFECT_RED_VEHS, EFFECT_GREEN_VEHS, EFFECT_RAINBOW_VEHS, EFFECT_VEHS_INVISIBLE, EFFECT_PINK_VEHS }}},
	{EFFECT_GREEN_VEHS, {"Trafico Verde", "vehs_green", true, { EFFECT_RED_VEHS, EFFECT_BLUE_VEHS, EFFECT_RAINBOW_VEHS, EFFECT_VEHS_INVISIBLE, EFFECT_PINK_VEHS }}},
	{EFFECT_CHROME_VEHS, {"Trafico Cromado", "vehs_chrome", true, { EFFECT_RED_VEHS, EFFECT_BLUE_VEHS, EFFECT_GREEN_VEHS, EFFECT_RAINBOW_VEHS, EFFECT_VEHS_INVISIBLE, EFFECT_PINK_VEHS }}},
	{EFFECT_PINK_VEHS, {"Trafico Rosa", "vehs_pink", true, { EFFECT_VEHS_INVISIBLE, EFFECT_CHROME_VEHS }}},
	{EFFECT_RAINBOW_VEHS, {"Trafico Arcoiris", "vehs_rainbow", true, { EFFECT_RED_VEHS, EFFECT_BLUE_VEHS, EFFECT_GREEN_VEHS, EFFECT_VEHS_INVISIBLE, EFFECT_PINK_VEHS }}},
	{EFFECT_FORCED_FP, {"Primera Persona", "player_firstperson", true, { EFFECT_FORCED_CINEMATIC }}},
	{EFFECT_SLIPPERY_VEHS, {"Vehiculos Resbalosos", "vehs_slippery", true}},
	{EFFECT_NO_GRAV_VEHS, {"Los Vehiculos No Tienen Gravedad", "vehs_nogravity", true, {}, true}},
	{EFFECT_PLAYER_INVINCIBLE, {"Invencibilidad", "player_invincible", true}},
	{EFFECT_2XENGINE_VEHS, {"Velocidad De Motor x2", "vehs_x2engine", true, { EFFECT_10XENGINE_VEHS, EFFECT_05XENGINE_VEHS }}},
	{EFFECT_10XENGINE_VEHS, {"Velocidad De Motor x10", "vehs_x10engine", true, { EFFECT_2XENGINE_VEHS, EFFECT_05XENGINE_VEHS }}},
	{EFFECT_05XENGINE_VEHS, {"Velocidad De Motor x0.5", "vehs_x05engine", true, { EFFECT_2XENGINE_VEHS, EFFECT_10XENGINE_VEHS }}},
	{EFFECT_SPAWN_TANK, {"Spawn Tanque", "spawn_rhino"}},
	{EFFECT_SPAWN_ADDER, {"Spawn Super Deportivo", "spawn_adder"}},
	{EFFECT_SPAWN_DUMP, {"Spawn Camion De Carga", "spawn_dump"}},
	{EFFECT_SPAWN_MONSTER, {"Spawn Monster Truck", "spawn_monster"}},
	{EFFECT_SPAWN_BMX, {"Spawn Bici", "spawn_bmx"}},
	{EFFECT_SPAWN_TUG, {"Spawn Barco De Pesca", "spawn_tug"}},
	{EFFECT_SPAWN_CARGO, {"Spawn Avion De Carga", "spawn_cargo"}},
	{EFFECT_SPAWN_BUS, {"Spawn Bus", "spawn_bus"}},



	{EFFECT_SPAWN_BLIMP, {"Spawn Zepelin", "spawn_blimp"}},
	{EFFECT_SPAWN_BUZZARD, {"Spawn Helicoptero De Combate", "spawn_buzzard"}},
	{EFFECT_SPAWN_FAGGIO, {"Spawn Motillo", "spawn_faggio"}},
	{EFFECT_SPAWN_RUINER3, {"Spawn Ruiner Arruinado", "spawn_ruiner3"}},
	{EFFECT_SPAWN_BALETRAILER, {"Spawn Trailer De Heno", "spawn_baletrailer"}},
	{EFFECT_SPAWN_ROMERO, {"Donde es el funeral?", "spawn_romero"}},
	{EFFECT_SPAWN_RANDOM, {"Spawn Vehiculo Aleatorio", "spawn_random"}},
	{EFFECT_NO_VEHS, {"Sin Trafico", "notraffic", true}},
	{EFFECT_EXPLODE_CUR_VEH, {"Reventar Vehiculo Actual", "playerveh_explode"}},
	{EFFECT_PEDS_INVISIBLE, {"Todo El Mundo Es Un Fantasma", "peds_ghost", true}},
	{EFFECT_VEHS_INVISIBLE, {"Vehiculos Invisibles", "vehs_ghost", true, { EFFECT_RED_VEHS, EFFECT_BLUE_VEHS, EFFECT_GREEN_VEHS, EFFECT_RAINBOW_VEHS, EFFECT_RAINBOW_VEHS }}},
	{EFFECT_NO_RADAR, {"Sin Radar", "no_radar", true, { EFFECT_NO_HUD }}},
	{EFFECT_NO_HUD, {"Sin Interfaz", "no_hud", true, { EFFECT_NO_RADAR } }},
	{EFFECT_SUPER_RUN, {"Super Carrera & Super Salto", "player_superrun", true }},
	{EFFECT_PLAYER_RAGDOLL, {"El Jugador Se Cae", "player_ragdoll", false, { EFFECT_NO_RAGDOLL }}},
	{EFFECT_PEDS_RAGDOLL_ON_TOUCH, {"Sensible A Los Roces", "peds_sensitivetouch", true, { EFFECT_NO_RAGDOLL }, true}},
	{EFFECT_PLAYER_POOR, {"Bancarrota", "poorboi"}},
	{EFFECT_PEDS_FOLLOW_PLAYER, {"Eres Famoso", "player_famous", true}},
	{EFFECT_PLAYER_DRUNK, {"Borracho", "player_drunk", true}},
	{EFFECT_PEDS_OHKO, {"1 De Vida", "player_ohko", true}},
	{EFFECT_SCREEN_LS_NOIRE, {"LS Noire", "screen_lsnoire", true, { EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT, EFFECT_SCREEN_BUBBLEVISION }}},
	{EFFECT_SCREEN_BLOOM, {"Bloom", "screen_bloom", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_LSD, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT, EFFECT_SCREEN_BUBBLEVISION }}},
	{EFFECT_SCREEN_LSD, {"LSD", "screen_lsd", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT, EFFECT_SCREEN_BUBBLEVISION }}},
	{EFFECT_SCREEN_RENDERDIST, {"Donde Han Ido Todos?", "screen_lowrenderdist", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT, EFFECT_SCREEN_BUBBLEVISION }, true}},
	{EFFECT_SCREEN_FOG, {"Niebla Extrema", "screen_fog", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT, EFFECT_SCREEN_BUBBLEVISION }, true}},
	{EFFECT_SCREEN_BRIGHT, {"Vision Frita", "screen_bright", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT, EFFECT_SCREEN_BUBBLEVISION }, true}},
	{EFFECT_SCREEN_MEXICO, {"Es Asi Como Se Ve Mexico?", "screen_mexico", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_FULLBRIGHT, EFFECT_SCREEN_BUBBLEVISION }}},
	{EFFECT_SCREEN_FULLBRIGHT, {"A Tope De Brillo", "screen_fullbright", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_BUBBLEVISION }}},
	{EFFECT_SCREEN_BUBBLEVISION, {"Vision De Burbuja", "screen_bubblevision", true, { EFFECT_SCREEN_LS_NOIRE, EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT }, true}},
	{EFFECT_SCREEN_NEED_GLASSES, {"Se Me Han Olvidado Las Gafas", "screen_needglasses", true, { EFFECT_SCREEN_LSD, EFFECT_SCREEN_BLOOM, EFFECT_SCREEN_RENDERDIST, EFFECT_SCREEN_FOG, EFFECT_SCREEN_BRIGHT, EFFECT_SCREEN_MEXICO, EFFECT_SCREEN_FULLBRIGHT }, true}},
	{EFFECT_PEDS_BLIND, {"Personajes Cegatos", "peds_blind", true}},
	{EFFECT_HONK_BOOSTING, {"Turbo Claxon", "vehs_honkboost", true}},
	{EFFECT_MIN_DAMAGE, {"No Hay Dolor", "peds_mindmg", true}},
	{EFFECT_PEDS_FROZEN, {"Personajes Bobos", "peds_frozen", true}},
	{EFFECT_LOW_GRAV, {"Baja Gravedad", "lowgravity", true, { EFFECT_VERY_LOW_GRAV, EFFECT_INSANE_GRAV, EFFECT_INVERT_GRAV }, true}},
	{EFFECT_VERY_LOW_GRAV, {"Muy Baja Gravedad", "verylowgravity", true, { EFFECT_LOW_GRAV, EFFECT_INSANE_GRAV, EFFECT_INVERT_GRAV }, true}},
	{EFFECT_INSANE_GRAV, {"Gravedad Insana", "insanegravity", true, { EFFECT_LOW_GRAV, EFFECT_VERY_LOW_GRAV, EFFECT_INVERT_GRAV }, true}},
	{EFFECT_INVERT_GRAV, {"Gravedad Invertida", "invertgravity", true, { EFFECT_LOW_GRAV, EFFECT_VERY_LOW_GRAV, EFFECT_INSANE_GRAV }, true}},
	{EFFECT_VEH_REPAIR, {"Reparar Todos Los Vehiculos", "playerveh_repair"}},
	{EFFECT_VEH_POP_TIRES, {"Reventar Todos Los Neumaticos", "playerveh_poptires"}},
	{EFFECT_ALL_VEH_POP_TIRES, {"Esto Si Que Son Neumaticos Reventando", "vehs_poptiresconstant", true, {}, true}},
	{EFFECT_NO_SPECIAL_ABILITY, {"Sin Habilidad especial", "player_nospecial", true}},
	{EFFECT_IN_THE_HOOD, {"Temazo, Loco", "peds_dance", true}},
	{EFFECT_FORCED_CINEMATIC, {"Camara Cinematica En Vehiculos", "player_forcedcinematiccam", true, { EFFECT_FORCED_FP }}},
	{EFFECT_PEDS_FLEE, {"Todos Huyen", "peds_flee"}},
	{EFFECT_BREAK_VEH_DOORS, {"Romper Todas Las Puertas", "playerveh_breakdoors"}},
	{EFFECT_ZOMBIES, {"Zombies Explosivos", "zombies", true}},
	{EFFECT_METEOR_RAIN, {"Ducha De Meteoritos", "meteorrain", true}},
	{EFFECT_BLACKOUT, {"Apagon", "world_blackout", true}},
	{EFFECT_QUICK_TIME, {"Timelapse", "time_quickday", true}},
	{EFFECT_MOV_NO_UD, {"Desactivar Movimiento Adelante / Atras", "player_noforwardbackward", true, {}, true}},
	{EFFECT_MOV_NO_LR, {"Desactivar Movimiento Izquierda / Derecha", "player_noleftright", true, {}, true}},
	{EFFECT_PLAYER_AUTOPILOT, {"Piloto Automatico", "player_break", true, {}, true}},
	{EFFECT_EVERYONE_RPG, {"Dar A Todos Un RPG", "peds_giverpg"}},
	{EFFECT_EVERYONE_TAZER, {"Dar A Todos Una Taser", "peds_stungun"}},
	{EFFECT_EVERYONE_MINIGUN, {"Dar A Todos Una Minigun", "peds_minigun"}},
	{EFFECT_EVERYONE_UPNATOMIZER, {"Dar A Todos Un Arma Alienigena", "peds_upnatomizer"}},
	{EFFECT_EVERYONE_RANDOMWEP, {"Dar A Todos Un Arma Aleatoria", "peds_randomwep"}},
	{EFFECT_EVERYONE_RAILGUN, {"Dar A Todos Un Arma De Rayos", "peds_railgun"}},
	{EFFECT_EVERYONE_BATTLEAXE, {"Dar A Todos Un Hacha De Batalla", "peds_battleaxe"}},
	{EFFECT_NO_SPRINT_JUMP, {"Sin Sprint & Sin Salto", "player_nosprint", true}},
	{EFFECT_EVERYONE_INVINCIBLE, {"Todo El Mundo Es Invencible", "peds_invincible", true}},
	{EFFECT_VEHS_INVINCIBLE, {"Vehiculos Invulnerables", "vehs_invincible", true}},
	{EFFECT_PLAYER_SHOT_RAGDOLL, {"Sensible A Los Tiros", "player_ragdollondmg", true, { EFFECT_NO_RAGDOLL }}},
	{EFFECT_JUMPY_VEHS, {"Vehiculos Saltarines", "vehs_jumpy", true, {}, true}},
	{EFFECT_LOCK_VEHS, {"Bloquear Todos Los Vehiculos", "vehs_lockdoors"}},
	{EFFECT_TOTAL_CHAOS, {"Dia Del Juicio Final", "chaosmode", true, {}, true}},
	{EFFECT_NO_RAGDOLL, {"Equilibrio De Acero", "player_noragdoll", true}},
	{EFFECT_VEHS_HORN, {"Todos Los Vehiculos Pitan", "vehs_honkconstant", true}},
	{EFFECT_TP_WAYPOINT, {"Teletransporte Al Punto De Ruta", "player_tptowaypoint"}},
	{EFFECT_PEDS_SAY_HI, {"Vecindario Amigable", "peds_sayhi", true, { EFFECT_PEDS_INSULT }}},
	{EFFECT_PEDS_INSULT, {"Vecindario Desagradable", "peds_insult", true, { EFFECT_PEDS_SAY_HI }}},
	{EFFECT_EXPLOSIVE_COMBAT, {"Combate Explosivo", "player_explosivecombat", true}},
	{EFFECT_GIVE_ALL_WEPS, {"Dar Todas Las Armas", "player_allweps"}},
	{EFFECT_PEDS_AIMBOT, {"Ciudadanos Con Aimbot", "peds_aimbot", true}},
	{EFFECT_SPAWN_COMPANION_CHOP, {"Spawn Perro Aliado", "spawn_chop"}},
	{EFFECT_SPAWN_COMPANION_CHIMP, {"Spawn Simio Aliado", "spawn_chimp"}},
	{EFFECT_SPAWN_COMPANION_BRAD, {"Spawn Brad Aliado", "spawn_compbrad"}},
	{EFFECT_SPAWN_COMPANION_RANDOM, {"Spawn Aliado Aleatorio", "spawn_comprnd"}},
	{EFFECT_PLAYER_NIGHTVISION, {"Vision Nocturna", "player_nightvision", true}},
	{EFFECT_PLAYER_HEATVISION, {"Vision Termica", "player_heatvision", true, {}, true}},
	{EFFECT_PLAYER_MONEYDROPS, {"Lluvia De Dinero", "player_moneydrops", true}},
	{EFFECT_VEH_TPRANDOMPEDS, {"Meter Gente Aleatoria En El Vehiculo", "playerveh_tprandompeds"}},
	{EFFECT_PEDS_REVIVE, {"Revivir Personajes Muertos", "peds_revive"}},
	{EFFECT_SNOW, {"Nieve", "world_snow", true}},
	{EFFECT_WHALE_RAIN, {"Lluvia De Ballenas", "world_whalerain", true}},
	{EFFECT_VEH_MAX_UPGRADES, {"Mejorar Todos Los Vehiculos Al Maximo", "playerveh_maxupgrades"}},
	{EFFECT_VEH_RANDOM_UPGRADES, {"Mejorar Todos Los Vehiculos Aleatoriamente", "playerveh_randupgrades"}},
	{EFFECT_INTENSE_MUSIC, {"Reproducir Cancion De Arena Wars", "player_arenawarstheme", true}},
	{EFFECT_PEDS_DRIVEBY, {"Te Disparan Desde El Coche", "peds_driveby", true, {}, true}},
	{EFFECT_PLAYER_RANDOMCLOTHES, {"Ropa Aleatoria", "player_randclothes"}},
	{EFFECT_PEDS_RAINBOWWEPS, {"Armas Arcoiris", "peds_rainbowweps", true}},
	{EFFECT_GTAO_TRAFFIC, {"Iman De Trafico", "traffic_gtao", true}},
	{EFFECT_SPAWN_IE_SULTAN, {"Spawn Sultan Azul Enemigo", "spawn_bluesultan"}},
	{EFFECT_PLAYER_SETINTORANDVEH, {"Meter Jugador En Vehiculo Aleatorio", "player_setintorandveh"}},
	{EFFECT_VEHS_FULLACCEL, {"Gas, Gas, Gas", "traffic_fullaccel", true, {}, true}},
	{EFFECT_SPAWN_UFO, {"Spawn OVNI", "misc_spawnufo"}},
	{EFFECT_SPAWN_FERRISWHEEL, {"Spawn Noria", "misc_spawnferriswheel"}},
	{EFFECT_EXPLOSIVE_PEDS, {"Peatones Explosivos", "peds_explosive", true}},
	{EFFECT_INVERTVELOCITY, {"Invertir Velocidad Actual", "invertvelocity"}},
	{EFFECT_PLAYER_TPEVERYTHING, {"Traer Todo Al Jugador", "player_tpeverything"}},
	{EFFECT_WEATHER_RANDOMWEATHER, {"Clima Disco", "weather_randomizer", true}},
	{EFFECT_LOW_POLY, {"Graficos De PS1", "world_lowpoly", true}},
	{EFFECT_NEARBY_PEDS_OBLITERATE, {"Todos Los Peatones Explotan", "peds_obliterate"}},
	{EFFECT_VEHS_TRIGGER_ALARM, {"Suenan Las Alarmas", "vehs_alarmloop", true}},
	{EFFECT_TP_FRONT, {"Teletransportar Jugador Adelante", "player_tpfront"}},
	{EFFECT_SPAWN_FAN_CATS, {"Spawn Gatos Amistosos", "peds_spawnfancats"}},
	{EFFECT_PEDS_COPS, {"Todos Los Peatones Son Policias", "peds_cops", true, {EFFECT_PEDS_RIOT }}},
	{EFFECT_ROT_ALL_VEHS, {"Voltear Todos Los Vehiculos", "vehs_rotall"}},
	{EFFECT_LAUNCH_ALL_PEDS, {"Lanzar Peatones Arriba", "peds_launchnearby"}},
	{EFFECT_PEDS_ATTACK_PLAYER, {"Todos Atacan Al Jugador", "peds_attackplayer", true}},
	{EFFECT_CLONE_PLAYER, {"Clonar Jugador", "player_clone"}},
	{EFFECT_SLIDY_PEDS, {"Peatones Deslizantes", "peds_slidy", true, {}, true}},
	{EFFECT_VEH_SET_RANDOM_SEAT, {"Cambiar De Asiento Al Jugador", "veh_randomseat"}},
	{EFFECT_VEH_SET_TOPSPEED_30MPH, {"Limitador De Velocidad 30MPH", "veh_30mphlimit", true, {}, true}},
	{EFFECT_PEDS_RAGDOLL, {"Todos Se Caen", "peds_ragdoll", false, { EFFECT_NO_RAGDOLL }}},
	{EFFECT_JESUS_TAKE_THE_WHEEL, {"Jesus Coge El Volante", "veh_jesustakethewheel"}},
	{EFFECT_VEH_POP_TIRE_LOOP, {"Las Ruedas Estallan Aleatoriamente", "veh_poptire", true, {}, true}},
	{EFFECT_ANGRY_ALIEN, {"Spawn Alien Enfadado", "peds_angryalien"}},
	{EFFECT_ANGRY_JIMMY, {"Spawn Jimmy El Celoso", "peds_angryjimmy"}},
	{EFFECT_OHKO_VEHICLES, {"Vehiculos Explotan Al Impactar", "vehs_ohko", true}},
	{EFFECT_VEH_SPAM_DOORS, {"Puertas Automaticas", "vehs_spamdoors", true}},
	{EFFECT_VEH_SPEED_MINIMUM, {"Need For Speed", "veh_speed_goal", true, { EFFECT_VEH_SET_TOPSPEED_30MPH }, true}},
	{EFFECT_MISC_LESTER, {"Pwned", "misc_lester", true, { EFFECT_VEH_SPEED_MINIMUM }, true}},
	{EFFECT_MISC_CREDITS, {"Pasar Los Creditos", "misc_credits", true, {}, true}},
	{EFFECT_MISC_EARTHQUAKE, {"Terremoto", "misc_earthquake", true, {}, true}},
	{EFFECT_SPAWN_DANCING_APES, {"Spawn Simios Bailarines", "peds_spawndancingapes"}},
	{EFFECT_ONE_BULLET_WEP, {"Cargadores De Una Bala", "misc_onebullet", true}},
	{EFFECT_PHONES, {"De Quien Es El Movil?", "peds_phones", true}},
	{EFFECT_MIDAS_TOUCH, {"Toque Dorado", "misc_midas", true}},
	{EFFECT_SPAWN_RANDOM_HOSTILE, {"Spawn Enemigo Aleatorio", "peds_spawnrandomhostile"}},
	{EFFECT_SPAWN_BALLA_SQUAD, {"Spawn Grupo Balla", "peds_spawnballasquad"}},
	{EFFECT_VEH_NO_BRAKES, {"Sin Frenos", "playerveh_nobrakes", true}},
	{EFFECT_PEDS_PORTAL_GUN, {"Armas De Portales", "peds_portal_gun", true}},
	{EFFECT_MISC_FIREWORKS, {"Fuegos Artificiales!", "misc_fireworks", true}},
	{EFFECT_VEH_DESPAWN, {"Borrar Vehiculo Actual", "playerveh_despawn"}},
	{EFFECT_VEH_FLYING_CAR, {"Coches Voladores", "vehs_flyingcars", true}},
	{EFFECT_PEDS_SCOOTERBROTHERS, {"Hermanos De Motillo", "peds_scooterbrothers"}},
	{EFFECT_PEDS_INTORANDOMVEHS, {"Meter A Todos En Vehiculos Aleatorios", "peds_intorandomvehs"}},
	{EFFECT_PLAYER_HEAVY_RECOIL, { "Gran Retroceso De Las Armas", "player_heavyrecoil", true}},
	{EFFECT_PEDS_CAT_GUNS, {"Armas Gatunas", "peds_catguns", true}},
	{EFFECT_PLAYER_FORCEFIELD, {"Campo De Fuerza", "player_forcefield", true, {}, true}},
	{EFFECT_MISC_OIL_LEAKS, {"Rastros De Aceite", "misc_oilleaks", true}},
	{EFFECT_PEDS_GUNSMOKE, {"Armas Humeantes", "peds_gunsmoke", true}},
	{EFFECT_PLAYER_KEEP_RUNNING, {"Ayuda, No Puedo Parar", "player_keeprunning", true}},
	{EFFECT_VEH_WEAPONS, {"Vehiculos Con Lanzamisiles (Click Izquierdo/RB)", "veh_weapons", true}},
	{EFFECT_MISC_AIRSTRIKE, {"Ataque Aereo En Camino", "misc_airstrike", true}},
	{EFFECT_PEDS_MINIONS, {"Minions", "peds_minions", true}},
	{EFFECT_PEDS_MERCENARIES, {"Mercenarios", "peds_mercenaries", true}},
	{EFFECT_LOOSE_TRIGGER, {"Gatillo Suelto", "peds_loosetrigger", true}},
	{EFFECT_MISC_FLAMETHROWER, {"Lanzallamas", "misc_flamethrower", true}},
	{EFFECT_MISC_DVDSCREENSAVER, {"Fondo De Pantalla DVD", "misc_dvdscreensaver", true, {}, true}},
	{EFFECT_PLAYER_FAKEDEATH, {"Muerte Falsa", "player_fakedeath"}},
	{EFFECT_GAMESPEED_SUPERHOT, {"Superhot", "time_superhot", true}},
	{EFFECT_PLAYER_KICKFLIP, {"Kickflip", "player_kickflip"}},
	{EFFECT_VEH_BEYBLADE, {"Beyblades", "vehs_beyblade", true, {}, true}},
	{EFFECT_KILLER_CLOWNS, {"Payasos Asesinos", "peds_killerclowns", true, {}, true}},
	{EFFECT_JAMES_BOND, {"Spawn Agente Mortifero", "peds_jamesbond"}},
	{EFFECT_PLAYER_POOF, {"Punteria Letal", "player_poof", true}},
	{EFFECT_PLAYER_SIMEONSAYS, {"Simeon Dice", "player_simeonsays", true, {}, true}},
	{EFFECT_VEH_LOCKCAMERA,  {"Bloquear Camara En Vehiculos", "veh_lockcamera", true}},
	{EFFECT_VEH_REPLACEVEHICLE, {"Intercambiar Vehiculo Actual", "misc_replacevehicle"}},
	{EFFECT_PLAYER_TIRED,  {"Estoy Tan Cansado...", "player_tired", true}},
	{EFFECT_MISC_SUPER_STUNT, {"Super Acrobacia", "misc_superstunt"}},
	{EFFECT_FLIP_CAMERA, {"Camara Invertida", "player_flip_camera", true, { EFFECT_PLAYER_QUAKE_FOV, EFFECT_PLAYER_GTA_2 }, true}},
	{EFFECT_PLAYER_QUAKE_FOV, {"Campo De Vision A Tope", "player_quake_fov", true, { EFFECT_FLIP_CAMERA, EFFECT_PLAYER_GTA_2 }}},
	{EFFECT_PLAYER_WALK_ON_WATER, {"Andar Sobre El Agua", "player_walkonwater", true }},
	{EFFECT_RAPID_FIRE, {"Fuego Rapido", "player_rapid_fire", true}},
	{EFFECT_PLAYER_ON_DEMAND_CARTOON, {"Netflix And Chill", "player_on_demand_cartoon", true}},
	{EFFECT_PEDS_DRIVE_BACKWARDS, {"Ciudadanos Conducen Marcha Atras", "peds_drive_backwards", true}},
	{EFFECT_VEH_RANDTRAFFIC, {"Trafico Aleatorio", "veh_randtraffic", true, {}, true}},
	{EFFECT_MISC_RAMPJAM, {"Salto Con Rampa (Pulsa Saltar En Un Vehiculo)", "misc_rampjam", true}},
	{EFFECT_MISC_VEHICLE_RAIN, {"Lluvia De Vehiculos", "misc_vehicle_rain", true, {}, true}},
	{EFFECT_MISC_CRASH, {"Crasheo Falso", "misc_fakecrash"}},
	{EFFECT_PLAYER_GRAVITY, {"Campo Gravitatorio", "player_gravity", true, {}, true}},
	{EFFECT_VEH_BOUNCY, {"Vehiculos Rebotantes", "veh_bouncy", true, {}, false}},
	{EFFECT_PEDS_STOP_AND_STARE, {"Parate Y Mira", "peds_stop_stare"}},
	{EFFECT_PEDS_FLIP, {"Peatones Rotatorios", "peds_flip", true}},
	{EFFECT_PLAYER_PACIFIST, {"Pacifista", "player_pacifist", true, {}, false}},
	{EFFECT_PEDS_BUSBOIS, {"Los Chicos Del Bus", "peds_busbois"}},
	{EFFECT_PLAYER_HACKING, {"Hackeo Realista", "player_hacking"}},
	{EFFECT_PEDS_NAILGUNS, {"Pistolas de clavos", "peds_nailguns", true, {}, true}},
	{EFFECT_VEH_BRAKEBOOST, {"Turbo Freno", "veh_brakeboost", true}},
	{EFFECT_PLAYER_BEES, {"ABEJAS!", "player_bees", true, { EFFECT_PEDS_OHKO }}},
	{EFFECT_PLAYER_VR, {"Modo VR", "player_vr", true, {}, true}},
	{EFFECT_MISC_PORTRAIT_MODE, {"Modo Retrato", "misc_portrait", true}},
	{EFFECT_HIGH_PITCH, {"Te Me Bajas 2 Tonitos, nota", "misc_highpitch", true, { EFFECT_GAMESPEED_X02, EFFECT_GAMESPEED_X05 }}},
	{EFFECT_NO_SKY, {"Sin Cielo", "misc_nosky", true}},
	{EFFECT_PLAYER_GTA_2, {"GTA 2", "player_gta_2", true, { EFFECT_PLAYER_QUAKE_FOV, EFFECT_FLIP_CAMERA }, true}},
	{EFFECT_PEDS_KIFFLOM, {"Kifflom!", "peds_kifflom", true}},
	{EFFECT_META_TIMER_SPEED_X0_5, {"Velocidad x0.5 De Cuenta Atras", "meta_timerspeed_0_5x", true, { EFFECT_META_TIMER_SPEED_X2, EFFECT_META_TIMER_SPEED_X5 }, false, EffectExecutionType::META}},
	{EFFECT_META_TIMER_SPEED_X2, {"Velocidad x2 De Cuenta Atras", "meta_timerspeed_2x", true, { EFFECT_META_TIMER_SPEED_X2, EFFECT_META_TIMER_SPEED_X5 }, false, EffectExecutionType::META}},
	{EFFECT_META_TIMER_SPEED_X5, {"Velocidad x5 De Cuenta Atras", "meta_timerspeed_5x", true, { EFFECT_META_TIMER_SPEED_X2, EFFECT_META_TIMER_SPEED_X5 }, true, EffectExecutionType::META}},
	{EFFECT_META_EFFECT_DURATION_X2, {"x2 Duracion De Efectos", "meta_effect_duration_2x", true, { EFFECT_META_EFFECT_DURATION_X0_5 }, false, EffectExecutionType::META}},
	{EFFECT_META_EFFECT_DURATION_X0_5, {"x0.5 Duracion De Efectos", "meta_effect_duration_0_5x", true, { EFFECT_META_EFFECT_DURATION_X2 }, false, EffectExecutionType::META}},
	{EFFECT_META_HIDE_CHAOS_UI, {"Que Esta Pasando??", "meta_hide_chaos_ui", true, {}, false, EffectExecutionType::META}},
	{EFFECT_META_ADDITIONAL_EFFECTS, {"Combo De Efectos", "meta_spawn_multiple_effects", true, {}, false, EffectExecutionType::META}},
	{EFFECT_VEHS_CRUMBLE, {"Vehiculos Hechos Chatarra", "vehs_crumble", true, {}, true}},
	{EFFECT_MISC_FPS_LIMIT, {"Experiencia De Consola", "misc_fps_limit", true, {}, true}},
	{EFFECT_META_NO_CHAOS, {"Sin Caos", "meta_nochaos", true, { EFFECT_META_HIDE_CHAOS_UI }, false, EffectExecutionType::META}},
	{EFFECT_PEDS_ROASTING, {"Humillacion", "peds_roasting", true, {}, true}}
};
